project_id = "zlfjxcwltqtajnczfjjp"

[functions.create-student-users]
verify_jwt = true

[functions.assign_tasks]
verify_jwt = true

[functions.generate-task-ai]
verify_jwt = true

[functions.reset-daily-credits]
verify_jwt = false

[functions.test-github-connection]
verify_jwt = false

[functions.verify-proof]
verify_jwt = false

[functions.github-check]
verify_jwt = false

[functions.ai-authorship]
verify_jwt = false

[functions.question-generator]
verify_jwt = false

[functions.submit-conceptual-answers]
verify_jwt = false

[functions.response-evaluator]
verify_jwt = false

[functions.trust-compute]
verify_jwt = false