project_id = "zlfjxcwltqtajnczfjjp"

[functions.create-student-users]
verify_jwt = true

[functions.assign_tasks]
verify_jwt = true

[functions.generate-task-ai]
verify_jwt = true

[functions.reset-daily-credits]
verify_jwt = false

[functions.test-github-connection]
verify_jwt = true