-- Replace the twelve function bodies Google was still running from before
-- stage75.
--
-- How this was missed: the earlier catch-up compared function NAMES and
-- ARGUMENTS. By that measure create_lot_for(uuid, date) existed on both sides
-- and looked fine. Inside, Google's version still walked the student's track,
-- their unlock wall and their weekly plan to choose a level, while Supabase's
-- picks a piece of source content - the whole point of stage75. Two functions
-- with the same signature and different bodies are two different functions,
-- and only the body says which.
--
-- The consequence, had it gone unnoticed: after the cutover every student would
-- have been served a lot chosen by the retired engine, quietly, with nothing
-- failing and no error anywhere.
--
-- Definitions below are Supabase's own, read out of the 12 September backup.
-- Regenerated by comparing md5(pg_get_functiondef(...)) on both sides, so the
-- list is computed rather than remembered.

begin;

-- Dropped before being recreated, not replaced. One of them changed its
-- return shape, and PostgreSQL refuses to replace a function whose OUT
-- parameters differ - so the whole set is dropped first, in one transaction,
-- rather than half of them being replaced and one failing.

drop function if exists public.assign_todays_lots();
drop function if exists public.claim_lot_template(_source_content_id uuid);
drop function if exists public.create_lot_for(_student_id uuid, _for_date date);
drop function if exists public.ensure_and_claim_lot_template(_source_content_id uuid);
drop function if exists public.lot_needs_writer(_task_id uuid);
drop function if exists public.my_todays_lot();
drop function if exists public.next_lot_source(_student_id uuid);
drop function if exists public.release_lot_template(_source_content_id uuid, _token uuid);
drop function if exists public.save_lot_template(_source_content_id uuid, _token uuid, _title text, _scenario text, _code_sample text, _source_jd text, _difficulty text, _estimate_minutes integer, _lot_category text, _sandbox_config_id uuid, _rubric_config_id uuid);
drop function if exists public.seed_lot_template(_source_content_id uuid);
drop function if exists public.start_task_assignment(_task_id uuid);
drop function if exists public.touch_lot_template(_source_content_id uuid, _token uuid);
-- next_lot_level is what create_lot_for used to call. stage75 dropped it on
-- Supabase; Google still has it, and dropping it here is what stops anything
-- silently falling back to the old path.
drop function if exists public.next_lot_level(uuid);

CREATE OR REPLACE FUNCTION public.assign_todays_lots()
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public', 'pg_temp'
AS $function$
declare s record; made integer := 0; skipped integer := 0; r jsonb;
begin
  for s in
    select p.id from public.student_profiles p
     where p.status = 'active'
  loop
    r := public.create_lot_for(s.id, current_date);
    if coalesce((r->>'created')::boolean, false) then made := made + 1;
    else skipped := skipped + 1; end if;
  end loop;
  return jsonb_build_object('ok', true, 'lots_created', made, 'already_had_one', skipped,
                            'ran_at', now());
end $function$
;

CREATE OR REPLACE FUNCTION public.claim_lot_template(_source_content_id uuid)
 RETURNS uuid
 LANGUAGE sql
 SECURITY DEFINER
 SET search_path TO 'public', 'pg_temp'
AS $function$
  with claimed as (
    update public.lot_templates
       set generating_since = now(), generating_by = gen_random_uuid()
     where source_content_id = _source_content_id
       and origin = 'seed'
       and (generating_since is null or generating_since < now() - interval '2 minutes')
    returning generating_by
  )
  select generating_by from claimed;
$function$
;

CREATE OR REPLACE FUNCTION public.create_lot_for(_student_id uuid, _for_date date DEFAULT NULL::date)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public', 'pg_temp'
AS $function$
declare
  d    date := coalesce(_for_date, current_date);
  scid uuid;
  tpl  record;
  n    integer;
  tid  uuid;
  cur  record;
begin
  select t.id, t.source_content_id
    into cur
    from public.tasks t
   where t.student_id = _student_id and t.lot_date = d
   limit 1;

  if cur.id is not null then
    return jsonb_build_object('ok', true, 'task_id', cur.id, 'created', false,
                              'source_content_id', cur.source_content_id,
                              'needs_writer', public.lot_needs_writer(cur.id));
  end if;

  scid := public.next_lot_source(_student_id);
  if scid is null then
    return jsonb_build_object('ok', true, 'task_id', null, 'created', false,
      'reason', 'no content available', 'needs_writer', false);
  end if;

  select * into tpl from public.lot_templates where source_content_id = scid;
  if tpl is null then
    perform public.seed_lot_template(scid);
    select * into tpl from public.lot_templates where source_content_id = scid;
  end if;
  if tpl is null then
    return jsonb_build_object('ok', false, 'reason', 'no template', 'needs_writer', false);
  end if;

  select count(*) + 1 into n from public.tasks
   where student_id = _student_id and lot_date is not null;

  insert into public.tasks
    (student_id, title, description, code_sample, source_jd, difficulty,
     estimate_minutes, lot_category, lot_number, lot_date, source_content_id,
     status, visibility, due_date, is_ai_generated, created_by_type, source,
     xp_reward, sandbox_config_id, rubric_config_id)
  values
    (_student_id, tpl.title, tpl.scenario, tpl.code_sample, tpl.source_jd, tpl.difficulty,
     tpl.estimate_minutes, tpl.lot_category, n, d, scid,
     'pending', 'private', (d + 1)::timestamptz - interval '1 second',
     tpl.origin = 'ai', 'system', 'daily_lot',
     tpl.xp_reward, tpl.sandbox_config_id, tpl.rubric_config_id)
  on conflict (student_id, lot_date) where lot_date is not null do nothing
  returning id into tid;

  if tid is null then
    select t.id, t.source_content_id into cur from public.tasks t
     where t.student_id = _student_id and t.lot_date = d limit 1;
    return jsonb_build_object('ok', true, 'task_id', cur.id, 'created', false,
                              'reason', 'another request created it first',
                              'source_content_id', cur.source_content_id,
                              'needs_writer', public.lot_needs_writer(cur.id));
  end if;

  return jsonb_build_object('ok', true, 'task_id', tid, 'created', true,
                            'source_content_id', scid, 'needs_writer', tpl.origin = 'seed');
end
$function$
;

CREATE OR REPLACE FUNCTION public.ensure_and_claim_lot_template(_source_content_id uuid)
 RETURNS uuid
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public', 'pg_temp'
AS $function$
begin
  if not exists (select 1 from public.lot_templates where source_content_id = _source_content_id) then
    perform public.seed_lot_template(_source_content_id);
  end if;
  return public.claim_lot_template(_source_content_id);
end $function$
;

CREATE OR REPLACE FUNCTION public.lot_needs_writer(_task_id uuid)
 RETURNS boolean
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public', 'pg_temp'
AS $function$
  select coalesce((select t.origin = 'seed'
                     from public.tasks k
                     join public.lot_templates t on t.source_content_id = k.source_content_id
                    where k.id = _task_id), false);
$function$
;

CREATE OR REPLACE FUNCTION public.my_todays_lot()
 RETURNS TABLE(id uuid, lot_number integer, title text, description text, code_sample text, source_jd text, difficulty text, estimate_minutes integer, lot_category text, status text, due_date timestamp with time zone, sponsored_by_company text, sandbox_config_id uuid, rubric_config_id uuid)
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public', 'pg_temp'
AS $function$
  select t.id, t.lot_number, t.title, t.description, t.code_sample, t.source_jd,
         t.difficulty, t.estimate_minutes, t.lot_category, t.status, t.due_date,
         r.company, t.sandbox_config_id, t.rubric_config_id
    from public.tasks t
    left join public.recruiters r on r.id = t.sponsored_by
   where t.student_id = auth.uid() and t.lot_date = current_date
   limit 1;
$function$
;

CREATE OR REPLACE FUNCTION public.next_lot_source(_student_id uuid)
 RETURNS uuid
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public', 'pg_temp'
AS $function$
  with mine as (
    select distinct k.source_content_id
      from public.tasks k
     where k.student_id = _student_id and k.source_content_id is not null
  ),
  my_college as (
    select college_id from public.student_profiles where id = _student_id
  ),
  fresh as (
    select sc.id
      from public.source_content sc
     where sc.id not in (select source_content_id from mine)
     order by
       (sc.submitted_by_college_id is not null
          and sc.submitted_by_college_id = (select college_id from my_college)) desc,
       (sc.submitted_by_college_id is not null) desc,
       sc.fetched_at asc
     limit 1
  ),
  reuse as (
    select sc.id
      from public.source_content sc
      left join public.tasks k
        on k.source_content_id = sc.id and k.student_id = _student_id
     group by sc.id
     order by max(k.lot_date) asc nulls first
     limit 1
  )
  select coalesce((select id from fresh), (select id from reuse));
$function$
;

CREATE OR REPLACE FUNCTION public.release_lot_template(_source_content_id uuid, _token uuid)
 RETURNS void
 LANGUAGE sql
 SECURITY DEFINER
 SET search_path TO 'public', 'pg_temp'
AS $function$
  update public.lot_templates
     set generating_since = null, generating_by = null
   where source_content_id = _source_content_id and generating_by = _token;
$function$
;

CREATE OR REPLACE FUNCTION public.save_lot_template(_source_content_id uuid, _token uuid, _title text, _scenario text, _code_sample text, _source_jd text, _difficulty text, _estimate_minutes integer, _lot_category text, _sandbox_config_id uuid DEFAULT NULL::uuid, _rubric_config_id uuid DEFAULT NULL::uuid)
 RETURNS boolean
 LANGUAGE sql
 SECURITY DEFINER
 SET search_path TO 'public', 'pg_temp'
AS $function$
  with saved as (
    update public.lot_templates
       set title = _title, scenario = _scenario, code_sample = _code_sample,
           source_jd = _source_jd, difficulty = _difficulty,
           estimate_minutes = _estimate_minutes, lot_category = _lot_category,
           sandbox_config_id = _sandbox_config_id, rubric_config_id = _rubric_config_id,
           origin = 'ai', generating_since = null, generating_by = null,
           updated_at = now()
     where source_content_id = _source_content_id and generating_by = _token
    returning 1
  )
  select exists (select 1 from saved);
$function$
;

CREATE OR REPLACE FUNCTION public.seed_lot_template(_source_content_id uuid)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public', 'pg_temp'
AS $function$
declare
  c record;
  fallback_rubric uuid;
begin
  select * into c from public.source_content where id = _source_content_id;
  if c is null then return; end if;

  select id into fallback_rubric from public.task_rubric_config where is_generic_fallback limit 1;

  insert into public.lot_templates
    (source_content_id, title, scenario, difficulty, estimate_minutes, lot_category, origin, rubric_config_id)
  values (
    _source_content_id,
    coalesce(c.title, 'Today''s real question'),
    'Build the smallest working thing that proves you understand ' ||
      coalesce(c.title, 'this') || '. Submit what you built, then record sixty ' ||
      'seconds explaining why your approach is right and what you would do ' ||
      'differently with more time.',
    'Medium',
    20,
    'technical',
    'seed',
    fallback_rubric)
  on conflict (source_content_id) do nothing;
end $function$
;

CREATE OR REPLACE FUNCTION public.start_task_assignment(_task_id uuid)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public', 'pg_temp'
AS $function$
declare
  caller     uuid := auth.uid();
  profile_id uuid;
  t          record;
  prev       text;
begin
  if caller is null then
    return jsonb_build_object('ok', false, 'reason', 'not authenticated');
  end if;

  select id into profile_id from public.student_profiles where user_id = caller;
  if profile_id is null then
    return jsonb_build_object('ok', false, 'reason', 'no student profile');
  end if;

  select id, student_id into t from public.tasks where id = _task_id;
  if t.id is null then
    return jsonb_build_object('ok', false, 'reason', 'no such task');
  end if;

  prev := current_setting('app.system_write', true);
  perform set_config('app.system_write', 'on', true);

  if t.student_id = profile_id then
    -- Direct task, owned outright by this student.
    update public.tasks
       set started_at = coalesce(started_at, now()), status = 'In Progress'
     where id = _task_id and started_at is null;
  else
    -- Assigned task: only this student's own assignment row may move, and
    -- only forward from 'assigned' - never off 'completed' or anything a
    -- reviewer set.
    update public.task_assignments
       set status = 'in_progress', updated_at = now()
     where task_id = _task_id and student_id = profile_id and status = 'assigned';

    if not found then
      perform set_config('app.system_write', coalesce(prev, ''), true);
      return jsonb_build_object('ok', false, 'reason', 'not assigned to you, or already started');
    end if;

    -- Several students can share one assigned task row. started_at here is
    -- just "somebody has begun this" for anything that reads it off tasks
    -- directly; the per-student truth lives on task_assignments.status
    -- above. First starter sets it, a later one does not reset it.
    update public.tasks
       set started_at = coalesce(started_at, now())
     where id = _task_id and started_at is null;
  end if;

  perform set_config('app.system_write', coalesce(prev, ''), true);
  return jsonb_build_object('ok', true);
end
$function$
;

CREATE OR REPLACE FUNCTION public.touch_lot_template(_source_content_id uuid, _token uuid)
 RETURNS boolean
 LANGUAGE sql
 SECURITY DEFINER
 SET search_path TO 'public', 'pg_temp'
AS $function$
  with beat as (
    update public.lot_templates set generating_since = now()
     where source_content_id = _source_content_id and generating_by = _token
    returning 1
  )
  select exists (select 1 from beat);
$function$
;

-- ---------------------------------------------------------------------------
-- refuse to commit unless the engine now points the right way
-- ---------------------------------------------------------------------------

do $$
begin
  if to_regprocedure('public.next_lot_level(uuid)') is not null then
    raise exception 'next_lot_level still exists; the old path can still be reached';
  end if;

  if pg_get_functiondef(to_regprocedure('public.create_lot_for(uuid,date)')::oid)
     not ilike '%next_lot_source%' then
    raise exception 'create_lot_for is still not calling next_lot_source';
  end if;

  if pg_get_functiondef(to_regprocedure('public.create_lot_for(uuid,date)')::oid)
     ilike '%student_tracks%' then
    raise exception 'create_lot_for still reads student_tracks; lots are meant to be decoupled';
  end if;

  raise notice 'the daily-lot engine now matches Supabase: source-driven, no track lookup';
end $$;

commit;
