-- GENERATED by scripts/dev-tools/step6ee_build.py. Staging only. Always ROLLBACK.
begin;
-- REHEARSAL ONLY: put the expected production 'before' bodies in place (rolled back)
create or replace function public.recruiter_talent(
  _role text default null, _skills text[] default null, _branch text default null,
  _min_skill integer default null, _min_comms integer default null,
  _active_within integer default null, _limit integer default 50, _offset integer default 0
)
returns table(
  student_id uuid, full_name text, branch text, batch text, target_role text,
  total_xp integer, trust_score numeric, skills_proven bigint, skills_total bigint,
  top_skills text[], lots_done bigint, proofs_verified bigint, comms_score integer,
  explanations bigint, days_since_active integer, active_weeks bigint,
  squad_name text, squad_rank integer, season_points integer, shortlisted boolean,
  total_matches bigint
)
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  with me as (select public.my_recruiter_id() as rid,
                     public.is_verified_recruiter() as ok),
  candidates as (
    select p.id, p.full_name, p.branch, p.batch, p.target_role,
           p.total_xp, p.trust_score, p.last_active
      from public.student_profiles p
     where (select ok from me)
       and public.student_is_discoverable(p.id)
       and (_branch is null or lower(p.branch) = lower(_branch))
       and (_role   is null or p.target_role ilike '%' || _role || '%')
       and (_active_within is null
            or (p.last_active is not null
                and p.last_active >= now() - make_interval(days => _active_within)))
  ),
  enriched as (
    select c.*,
           (select count(*) from public.student_skills s
             where s.student_id = c.id and s.status = 'proven') as skills_proven,
           (select count(*) from public.student_skills s
             where s.student_id = c.id) as skills_total,
           (select coalesce(array_agg(s.skill order by
                      array_position(array['proven','assessed','claimed'], s.status), s.skill),
                    '{}')
              from public.student_skills s where s.student_id = c.id) as top_skills,
           (select max(s.assessed_score) from public.student_skills s
             where s.student_id = c.id) as best_skill_score,
           (select count(*) from public.tasks t
             where t.student_id = c.id and t.status in ('Completed','completed')) as lots_done,
           -- CHANGED (stage69): verified proofs + passed auto-graded submissions.
           (select count(*) from public.proof_uploads pu
             where pu.student_id = c.id and pu.status in ('Verified','verified'))
           + (select count(*) from public.task_submissions ts
             where ts.student_id = c.id and ts.status = 'passed') as proofs_verified,
           (select round(avg(v.communication_score))::integer from public.voice_explanations v
             where v.student_id = c.id and v.communication_score is not null) as comms_score,
           (select count(*) from public.voice_explanations v
             where v.student_id = c.id) as explanations,
           (select count(distinct w.week) from public.student_weekly_scores w
             where w.student_id = c.id and w.points > 0) as active_weeks,
           (select q.name from public.squad_members m
              join public.squads q on q.id = m.squad_id
             where m.student_id = c.id and m.left_at is null limit 1) as squad_name,
           (select q.rank from public.squad_members m
              join public.squads q on q.id = m.squad_id
             where m.student_id = c.id and m.left_at is null limit 1) as squad_rank,
           (select q.points from public.squad_members m
              join public.squads q on q.id = m.squad_id
             where m.student_id = c.id and m.left_at is null limit 1) as season_points,
           exists (select 1 from public.recruiter_shortlists sl
                    where sl.student_id = c.id
                      and sl.recruiter_id = (select rid from me)) as shortlisted
      from candidates c
  ),
  filtered as (
    select * from enriched e
     where (_min_skill is null or coalesce(e.best_skill_score, 0) >= _min_skill)
       and (_min_comms is null or coalesce(e.comms_score, 0)     >= _min_comms)
       and (_skills is null or exists (
              select 1 from public.student_skills s
               where s.student_id = e.id
                 and lower(s.skill) = any (select lower(x) from unnest(_skills) x)))
  )
  select f.id, f.full_name, f.branch, f.batch, f.target_role,
         f.total_xp, f.trust_score,
         f.skills_proven, f.skills_total, f.top_skills,
         f.lots_done, f.proofs_verified,
         f.comms_score, f.explanations,
         case when f.last_active is null then 999
              else (current_date - f.last_active::date) end,
         f.active_weeks,
         f.squad_name, f.squad_rank, f.season_points,
         f.shortlisted,
         count(*) over ()
    from filtered f
   order by f.skills_proven desc, f.proofs_verified desc, f.total_xp desc
   limit greatest(1, least(coalesce(_limit, 50), 100))
  offset greatest(0, coalesce(_offset, 0));
$$;

create or replace function public.recruiter_proof_profile(_student_id uuid)
returns jsonb language plpgsql stable security definer set search_path = public, pg_temp as $fn$
declare p record; rid uuid := public.my_recruiter_id(); accepted boolean;
begin
  if not public.is_verified_recruiter() then
    return jsonb_build_object('error', 'Your recruiter account is awaiting verification.');
  end if;

  if not public.student_is_discoverable(_student_id) then
    -- Deliberately the same answer as "no such student": whether a particular
    -- person is on this platform is itself something they did not consent to
    -- share.
    return jsonb_build_object('error', 'No candidate found.');
  end if;

  select * into p from public.student_profiles where id = _student_id;

  select sl.student_response = 'accepted' into accepted
    from public.recruiter_shortlists sl
   where sl.recruiter_id = rid and sl.student_id = _student_id;

  return jsonb_build_object(
    'id', p.id,
    'full_name', p.full_name,
    'branch', p.branch,
    'batch', p.batch,
    'year_of_study', p.year_of_study,
    'target_role', p.target_role,
    'secondary_roles', p.secondary_roles,
    'work_preference', p.work_preference,
    'preferred_locations', p.preferred_locations,
    'open_to_relocate', p.open_to_relocate,
    'total_xp', p.total_xp,
    'trust_score', p.trust_score,
    'last_active', p.last_active,
    'days_since_active', case when p.last_active is null then 999
                              else (current_date - p.last_active::date) end,

    'contact_unlocked', coalesce(accepted, false),
    'contact', case when coalesce(accepted, false) then
        (select jsonb_build_object('email', c.email, 'phone', c.phone,
                                   'github', c.github_url, 'linkedin', c.linkedin_url)
           from public.student_contact c where c.student_id = p.id)
      else null end,

    'skills', (select coalesce(jsonb_agg(jsonb_build_object(
                 'skill', s.skill, 'status', s.status, 'score', s.assessed_score,
                 'lots', s.proven_lots, 'explanations', s.proven_voice,
                 'last_evidence_at', s.last_evidence_at)
                 order by array_position(array['proven','assessed','claimed','needs_improvement'],
                                         s.status), s.skill), '[]'::jsonb)
                 from public.student_skills s where s.student_id = p.id),

    'certifications', (select coalesce(jsonb_agg(jsonb_build_object(
                         'name', t.name, 'issuer', t.issuer, 'issued_on', t.issued_on,
                         'url', t.credential_url, 'source', t.source)
                         order by t.issued_on desc nulls last), '[]'::jsonb)
                         from public.student_certifications t where t.student_id = p.id),

    'scorecard', (select jsonb_build_object(
                    'resume_quality', s.resume_quality_score,
                    'ats_match', s.ats_match_score,
                    'skill_proof', s.skill_proof_score,
                    'project_proof', s.project_proof_score,
                    'reasoning', s.reasoning_score,
                    'coding', s.coding_score,
                    'interview_readiness', s.interview_readiness_score,
                    'skill_gap', s.skill_gap,
                    'at', s.created_at)
                    from public.resume_scorecards s
                   where s.student_id = p.id order by s.created_at desc limit 1),

    'work', (select coalesce(jsonb_agg(w order by w.submitted_at desc), '[]'::jsonb) from (
        select pu.id, pu.status, pu.ai_score, pu.submitted_at,
               (select t.title from public.tasks t where t.id = pu.task_id) as title,
               (select t.difficulty from public.tasks t where t.id = pu.task_id) as difficulty
          from public.proof_uploads pu
         where pu.student_id = p.id and pu.is_public = true
         order by pu.submitted_at desc nulls last limit 10) w),

    'explanations', (select coalesce(jsonb_agg(v order by v.created_at desc), '[]'::jsonb) from (
        select ve.id, ve.duration_seconds, ve.communication_score,
               ve.communication_notes, ve.created_at,
               (select t.title from public.tasks t where t.id = ve.task_id) as about
          from public.voice_explanations ve
         where ve.student_id = p.id and ve.communication_score is not null
         order by ve.created_at desc limit 5) v),

    'communication', (select round(avg(v.communication_score))::integer
                        from public.voice_explanations v
                       where v.student_id = p.id and v.communication_score is not null),

    -- Consistency as weeks actually turned up, not a streak a single good
    -- fortnight can inflate.
    'consistency', jsonb_build_object(
      'active_weeks', (select count(*) from public.student_weekly_scores w
                        where w.student_id = p.id and w.points > 0),
      'weeks_total',  (select count(distinct w.week) from public.student_weekly_scores w
                        where w.student_id = p.id),
      'current_streak', (select current_days from public.student_streaks st
                          where st.student_id = p.id),
      'lots_done', (select count(*) from public.tasks t
                     where t.student_id = p.id and t.status in ('Completed','completed'))),

    'squad', (select jsonb_build_object(
                'name', q.name, 'rank', q.rank, 'points', q.points,
                'record', q.wins || '-' || q.draws || '-' || q.losses,
                'contribution', m.contribution)
                from public.squad_members m
                join public.squads q on q.id = m.squad_id
               where m.student_id = p.id and m.left_at is null limit 1),

    'ladder', jsonb_build_object(
      'track', (select t.track_slug from public.student_tracks t
                 where t.student_id = p.id order by t.created_at desc limit 1),
      'cleared', (select count(*) from public.student_levels sl
                   where sl.student_id = p.id and sl.status in ('cleared','mastered'))),

    'shortlist', (select jsonb_build_object('stage', sl.stage,
                          'response', sl.student_response, 'note', sl.note)
                    from public.recruiter_shortlists sl
                   where sl.recruiter_id = rid and sl.student_id = p.id)
  );
end $fn$;


set local lock_timeout = '5s';

do $$
declare v text;
begin
  -- exactly one of each, with the expected signatures and return types
  if (select count(*) from pg_proc where pronamespace = 'public'::regnamespace and proname = 'recruiter_talent') <> 1
     or (select count(*) from pg_proc where pronamespace = 'public'::regnamespace and proname = 'recruiter_proof_profile') <> 1 then
    raise exception 'pre-check: expected exactly one recruiter_talent and one recruiter_proof_profile';
  end if;
  if to_regprocedure('public.recruiter_talent(text, text[], text, integer, integer, integer, integer, integer)') is null or to_regprocedure('public.recruiter_proof_profile(uuid)') is null then
    raise exception 'pre-check: recruiter_talent / recruiter_proof_profile signature not found';
  end if;
  if pg_get_function_result('public.recruiter_talent(text, text[], text, integer, integer, integer, integer, integer)'::regprocedure) <> 'TABLE(student_id uuid, full_name text, branch text, batch text, target_role text, total_xp integer, trust_score numeric, skills_proven bigint, skills_total bigint, top_skills text[], lots_done bigint, proofs_verified bigint, comms_score integer, explanations bigint, days_since_active integer, active_weeks bigint, squad_name text, squad_rank integer, season_points integer, shortlisted boolean, total_matches bigint)' then
    raise exception 'pre-check: recruiter_talent return type differs: %', pg_get_function_result('public.recruiter_talent(text, text[], text, integer, integer, integer, integer, integer)'::regprocedure);
  end if;
  if pg_get_function_result('public.recruiter_proof_profile(uuid)'::regprocedure) <> 'jsonb' then
    raise exception 'pre-check: recruiter_proof_profile does not return jsonb';
  end if;

  -- already applied? (either the original 46 body or this one)
  if (select position('transcript_source' in prosrc) from pg_proc where oid = 'public.recruiter_talent(text, text[], text, integer, integer, integer, integer, integer)'::regprocedure) > 0
     or (select position('transcript_source' in prosrc) from pg_proc where oid = 'public.recruiter_proof_profile(uuid)'::regprocedure) > 0 then
    raise exception 'pre-check: a transcript_source filter is already present - migration 46 (or a version of it) is already applied; refusing';
  end if;

  -- both functions carry the expected pre-check bodies (whitespace-normalised md5)
  select md5(btrim(regexp_replace(prosrc, '\s+', ' ', 'g'))) into v from pg_proc where oid = 'public.recruiter_talent(text, text[], text, integer, integer, integer, integer, integer)'::regprocedure;
  if v <> 'f7c1eef2f57c8d5b1f961ea76a661fda' then
    raise exception 'pre-check: recruiter_talent body md5 is % (expected f7c1eef2f57c8d5b1f961ea76a661fda)', v;
  end if;
  select md5(btrim(regexp_replace(prosrc, '\s+', ' ', 'g'))) into v from pg_proc where oid = 'public.recruiter_proof_profile(uuid)'::regprocedure;
  if v <> 'b467d6f7769c61887d854fb4358cd30e' then
    raise exception 'pre-check: recruiter_proof_profile body md5 is % (expected b467d6f7769c61887d854fb4358cd30e)', v;
  end if;

  -- CREATE OR REPLACE keeps the owner; only the owner (or a member) may replace
  if not pg_has_role(current_user, (select proowner from pg_proc where oid = 'public.recruiter_talent(text, text[], text, integer, integer, integer, integer, integer)'::regprocedure), 'MEMBER')
     or not pg_has_role(current_user, (select proowner from pg_proc where oid = 'public.recruiter_proof_profile(uuid)'::regprocedure), 'MEMBER') then
    raise exception 'pre-check: % does not own recruiter_talent / recruiter_proof_profile', current_user;
  end if;

  -- objects the new bodies read must exist
  if not exists (select 1 from information_schema.columns where table_schema = 'public'
                  and table_name = 'voice_explanations' and column_name = 'transcript_source') then
    raise exception 'pre-check: voice_explanations.transcript_source missing';
  end if;
  if not exists (select 1 from pg_constraint where conrelid = 'public.voice_explanations'::regclass
                  and contype = 'c' and pg_get_constraintdef(oid) like '%transcript_source%'
                  and pg_get_constraintdef(oid) like '%''server''%') then
    raise exception 'pre-check: no CHECK on voice_explanations.transcript_source allowing ''server''';
  end if;
  if to_regclass('public.task_submissions') is null then
    raise exception 'pre-check: task_submissions (stage69) missing';
  end if;
  if to_regprocedure('public.my_recruiter_id()') is null or to_regprocedure('public.is_verified_recruiter()') is null
     or to_regprocedure('public.student_is_discoverable(uuid)') is null then
    raise exception 'pre-check: recruiter helper functions missing';
  end if;
  raise notice 'Step 6EE pre-checks passed: current bodies are stage69 talent + stage35c profile, 46 not applied.';
end $$;

-- snapshot every public function (body + ACL + owner) to prove afterwards
-- that only the two intended functions changed
create temp table _s6ee_before on commit drop as
  select p.oid, p.proname, md5(p.prosrc) as src_md5, p.proacl::text as acl, p.proowner,
         p.prosecdef, p.proconfig
    from pg_proc p where p.pronamespace = 'public'::regnamespace;

create or replace function public.recruiter_talent(
  _role text default null, _skills text[] default null, _branch text default null,
  _min_skill integer default null, _min_comms integer default null,
  _active_within integer default null, _limit integer default 50, _offset integer default 0
)
returns table(
  student_id uuid, full_name text, branch text, batch text, target_role text,
  total_xp integer, trust_score numeric, skills_proven bigint, skills_total bigint,
  top_skills text[], lots_done bigint, proofs_verified bigint, comms_score integer,
  explanations bigint, days_since_active integer, active_weeks bigint,
  squad_name text, squad_rank integer, season_points integer, shortlisted boolean,
  total_matches bigint
)
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  with me as (select public.my_recruiter_id() as rid,
                     public.is_verified_recruiter() as ok),
  candidates as (
    select p.id, p.full_name, p.branch, p.batch, p.target_role,
           p.total_xp, p.trust_score, p.last_active
      from public.student_profiles p
     where (select ok from me)
       and public.student_is_discoverable(p.id)
       and (_branch is null or lower(p.branch) = lower(_branch))
       and (_role   is null or p.target_role ilike '%' || _role || '%')
       and (_active_within is null
            or (p.last_active is not null
                and p.last_active >= now() - make_interval(days => _active_within)))
  ),
  enriched as (
    select c.*,
           (select count(*) from public.student_skills s
             where s.student_id = c.id and s.status = 'proven') as skills_proven,
           (select count(*) from public.student_skills s
             where s.student_id = c.id) as skills_total,
           (select coalesce(array_agg(s.skill order by
                      array_position(array['proven','assessed','claimed'], s.status), s.skill),
                    '{}')
              from public.student_skills s where s.student_id = c.id) as top_skills,
           (select max(s.assessed_score) from public.student_skills s
             where s.student_id = c.id) as best_skill_score,
           (select count(*) from public.tasks t
             where t.student_id = c.id and t.status in ('Completed','completed')) as lots_done,
           -- CHANGED (stage69): verified proofs + passed auto-graded submissions.
           (select count(*) from public.proof_uploads pu
             where pu.student_id = c.id and pu.status in ('Verified','verified'))
           + (select count(*) from public.task_submissions ts
             where ts.student_id = c.id and ts.status = 'passed') as proofs_verified,
           (select round(avg(v.communication_score))::integer from public.voice_explanations v
             where v.student_id = c.id and v.communication_score is not null
               -- Step 6H/6EE: only a server-transcribed explanation counts
               -- toward the score a recruiter sees and filters on.
               and v.transcript_source = 'server') as comms_score,
           (select count(*) from public.voice_explanations v
             where v.student_id = c.id) as explanations,
           (select count(distinct w.week) from public.student_weekly_scores w
             where w.student_id = c.id and w.points > 0) as active_weeks,
           (select q.name from public.squad_members m
              join public.squads q on q.id = m.squad_id
             where m.student_id = c.id and m.left_at is null limit 1) as squad_name,
           (select q.rank from public.squad_members m
              join public.squads q on q.id = m.squad_id
             where m.student_id = c.id and m.left_at is null limit 1) as squad_rank,
           (select q.points from public.squad_members m
              join public.squads q on q.id = m.squad_id
             where m.student_id = c.id and m.left_at is null limit 1) as season_points,
           exists (select 1 from public.recruiter_shortlists sl
                    where sl.student_id = c.id
                      and sl.recruiter_id = (select rid from me)) as shortlisted
      from candidates c
  ),
  filtered as (
    select * from enriched e
     where (_min_skill is null or coalesce(e.best_skill_score, 0) >= _min_skill)
       and (_min_comms is null or coalesce(e.comms_score, 0)     >= _min_comms)
       and (_skills is null or exists (
              select 1 from public.student_skills s
               where s.student_id = e.id
                 and lower(s.skill) = any (select lower(x) from unnest(_skills) x)))
  )
  select f.id, f.full_name, f.branch, f.batch, f.target_role,
         f.total_xp, f.trust_score,
         f.skills_proven, f.skills_total, f.top_skills,
         f.lots_done, f.proofs_verified,
         f.comms_score, f.explanations,
         case when f.last_active is null then 999
              else (current_date - f.last_active::date) end,
         f.active_weeks,
         f.squad_name, f.squad_rank, f.season_points,
         f.shortlisted,
         count(*) over ()
    from filtered f
   order by f.skills_proven desc, f.proofs_verified desc, f.total_xp desc
   limit greatest(1, least(coalesce(_limit, 50), 100))
  offset greatest(0, coalesce(_offset, 0));
$$;

create or replace function public.recruiter_proof_profile(_student_id uuid)
returns jsonb language plpgsql stable security definer set search_path = public, pg_temp as $fn$
declare p record; rid uuid := public.my_recruiter_id(); accepted boolean;
begin
  if not public.is_verified_recruiter() then
    return jsonb_build_object('error', 'Your recruiter account is awaiting verification.');
  end if;

  if not public.student_is_discoverable(_student_id) then
    -- Deliberately the same answer as "no such student": whether a particular
    -- person is on this platform is itself something they did not consent to
    -- share.
    return jsonb_build_object('error', 'No candidate found.');
  end if;

  select * into p from public.student_profiles where id = _student_id;

  select sl.student_response = 'accepted' into accepted
    from public.recruiter_shortlists sl
   where sl.recruiter_id = rid and sl.student_id = _student_id;

  return jsonb_build_object(
    'id', p.id,
    'full_name', p.full_name,
    'branch', p.branch,
    'batch', p.batch,
    'year_of_study', p.year_of_study,
    'target_role', p.target_role,
    'secondary_roles', p.secondary_roles,
    'work_preference', p.work_preference,
    'preferred_locations', p.preferred_locations,
    'open_to_relocate', p.open_to_relocate,
    'total_xp', p.total_xp,
    'trust_score', p.trust_score,
    'last_active', p.last_active,
    'days_since_active', case when p.last_active is null then 999
                              else (current_date - p.last_active::date) end,

    'contact_unlocked', coalesce(accepted, false),
    'contact', case when coalesce(accepted, false) then
        (select jsonb_build_object('email', c.email, 'phone', c.phone,
                                   'github', c.github_url, 'linkedin', c.linkedin_url)
           from public.student_contact c where c.student_id = p.id)
      else null end,

    'skills', (select coalesce(jsonb_agg(jsonb_build_object(
                 'skill', s.skill, 'status', s.status, 'score', s.assessed_score,
                 'lots', s.proven_lots, 'explanations', s.proven_voice,
                 'last_evidence_at', s.last_evidence_at)
                 order by array_position(array['proven','assessed','claimed','needs_improvement'],
                                         s.status), s.skill), '[]'::jsonb)
                 from public.student_skills s where s.student_id = p.id),

    'certifications', (select coalesce(jsonb_agg(jsonb_build_object(
                         'name', t.name, 'issuer', t.issuer, 'issued_on', t.issued_on,
                         'url', t.credential_url, 'source', t.source)
                         order by t.issued_on desc nulls last), '[]'::jsonb)
                         from public.student_certifications t where t.student_id = p.id),

    'scorecard', (select jsonb_build_object(
                    'resume_quality', s.resume_quality_score,
                    'ats_match', s.ats_match_score,
                    'skill_proof', s.skill_proof_score,
                    'project_proof', s.project_proof_score,
                    'reasoning', s.reasoning_score,
                    'coding', s.coding_score,
                    'interview_readiness', s.interview_readiness_score,
                    'skill_gap', s.skill_gap,
                    'at', s.created_at)
                    from public.resume_scorecards s
                   where s.student_id = p.id order by s.created_at desc limit 1),

    'work', (select coalesce(jsonb_agg(w order by w.submitted_at desc), '[]'::jsonb) from (
        select pu.id, pu.status, pu.ai_score, pu.submitted_at,
               (select t.title from public.tasks t where t.id = pu.task_id) as title,
               (select t.difficulty from public.tasks t where t.id = pu.task_id) as difficulty
          from public.proof_uploads pu
         where pu.student_id = p.id and pu.is_public = true
         order by pu.submitted_at desc nulls last limit 10) w),

    'explanations', (select coalesce(jsonb_agg(v order by v.created_at desc), '[]'::jsonb) from (
        select ve.id, ve.duration_seconds, ve.communication_score,
               ve.communication_notes, ve.created_at,
               (select t.title from public.tasks t where t.id = ve.task_id) as about
          from public.voice_explanations ve
         where ve.student_id = p.id and ve.communication_score is not null
           -- Step 6H/6EE: same provenance gate as recruiter_talent.comms_score
           and ve.transcript_source = 'server'
         order by ve.created_at desc limit 5) v),

    'communication', (select round(avg(v.communication_score))::integer
                        from public.voice_explanations v
                       where v.student_id = p.id and v.communication_score is not null
                         and v.transcript_source = 'server'),

    -- Consistency as weeks actually turned up, not a streak a single good
    -- fortnight can inflate.
    'consistency', jsonb_build_object(
      'active_weeks', (select count(*) from public.student_weekly_scores w
                        where w.student_id = p.id and w.points > 0),
      'weeks_total',  (select count(distinct w.week) from public.student_weekly_scores w
                        where w.student_id = p.id),
      'current_streak', (select current_days from public.student_streaks st
                          where st.student_id = p.id),
      'lots_done', (select count(*) from public.tasks t
                     where t.student_id = p.id and t.status in ('Completed','completed'))),

    'squad', (select jsonb_build_object(
                'name', q.name, 'rank', q.rank, 'points', q.points,
                'record', q.wins || '-' || q.draws || '-' || q.losses,
                'contribution', m.contribution)
                from public.squad_members m
                join public.squads q on q.id = m.squad_id
               where m.student_id = p.id and m.left_at is null limit 1),

    'ladder', jsonb_build_object(
      'track', (select t.track_slug from public.student_tracks t
                 where t.student_id = p.id order by t.created_at desc limit 1),
      'cleared', (select count(*) from public.student_levels sl
                   where sl.student_id = p.id and sl.status in ('cleared','mastered'))),

    'shortlist', (select jsonb_build_object('stage', sl.stage,
                          'response', sl.student_response, 'note', sl.note)
                    from public.recruiter_shortlists sl
                   where sl.recruiter_id = rid and sl.student_id = p.id)
  );
end $fn$;

-- permissions: recruiter-facing, so signed-in users only (stage35c's intent:
-- revoke from public, anon; grant to authenticated). Both functions check
-- is_verified_recruiter() themselves.
revoke execute on function public.recruiter_talent(text, text[], text, integer, integer, integer, integer, integer), public.recruiter_proof_profile(uuid) from public, anon;
grant execute on function public.recruiter_talent(text, text[], text, integer, integer, integer, integer, integer), public.recruiter_proof_profile(uuid) to authenticated;

do $$
declare v text; r record;
begin

  -- both functions carry the expected post-check bodies (whitespace-normalised md5)
  select md5(btrim(regexp_replace(prosrc, '\s+', ' ', 'g'))) into v from pg_proc where oid = 'public.recruiter_talent(text, text[], text, integer, integer, integer, integer, integer)'::regprocedure;
  if v <> 'd3ec3dda80922a036fc3d39460ced541' then
    raise exception 'post-check: recruiter_talent body md5 is % (expected d3ec3dda80922a036fc3d39460ced541)', v;
  end if;
  select md5(btrim(regexp_replace(prosrc, '\s+', ' ', 'g'))) into v from pg_proc where oid = 'public.recruiter_proof_profile(uuid)'::regprocedure;
  if v <> '2d048797e2d64852834c65ef4d24170a' then
    raise exception 'post-check: recruiter_proof_profile body md5 is % (expected 2d048797e2d64852834c65ef4d24170a)', v;
  end if;
  if (select position('task_submissions' in prosrc) from pg_proc where oid = 'public.recruiter_talent(text, text[], text, integer, integer, integer, integer, integer)'::regprocedure) = 0 then
    raise exception 'post-check: stage69 task_submissions count lost from recruiter_talent';
  end if;
  if pg_get_function_result('public.recruiter_talent(text, text[], text, integer, integer, integer, integer, integer)'::regprocedure) <> 'TABLE(student_id uuid, full_name text, branch text, batch text, target_role text, total_xp integer, trust_score numeric, skills_proven bigint, skills_total bigint, top_skills text[], lots_done bigint, proofs_verified bigint, comms_score integer, explanations bigint, days_since_active integer, active_weeks bigint, squad_name text, squad_rank integer, season_points integer, shortlisted boolean, total_matches bigint)'
     or pg_get_function_result('public.recruiter_proof_profile(uuid)'::regprocedure) <> 'jsonb' then
    raise exception 'post-check: return type changed';
  end if;

  for r in select p.oid, p.proname, p.prosecdef, p.proconfig, p.proowner, p.proacl, b.proowner as old_owner
             from pg_proc p join _s6ee_before b on b.oid = p.oid
            where p.oid in ('public.recruiter_talent(text, text[], text, integer, integer, integer, integer, integer)'::regprocedure, 'public.recruiter_proof_profile(uuid)'::regprocedure) loop
    if not r.prosecdef then raise exception 'post-check: % not SECURITY DEFINER', r.proname; end if;
    if r.proconfig is null or not ('search_path=public, pg_temp' = any (r.proconfig)) then
      raise exception 'post-check: % search_path not pinned (%)', r.proname, r.proconfig;
    end if;
    if r.proowner <> r.old_owner then raise exception 'post-check: % owner changed', r.proname; end if;
    if not has_function_privilege('authenticated', r.oid, 'EXECUTE') then
      raise exception 'post-check: authenticated lost EXECUTE on %', r.proname; end if;
    if has_function_privilege('anon', r.oid, 'EXECUTE') then
      raise exception 'post-check: anon can EXECUTE %', r.proname; end if;
    if exists (select 1 from aclexplode(coalesce(r.proacl, acldefault('f', r.proowner))) a where a.grantee = 0) then
      raise exception 'post-check: PUBLIC can EXECUTE %', r.proname; end if;
  end loop;

  -- nothing else changed: every other public function identical, none added or removed
  if exists (select 1 from _s6ee_before b join pg_proc p on p.oid = b.oid
              where b.oid not in ('public.recruiter_talent(text, text[], text, integer, integer, integer, integer, integer)'::regprocedure, 'public.recruiter_proof_profile(uuid)'::regprocedure)
                and (md5(p.prosrc) <> b.src_md5 or p.proacl::text is distinct from b.acl
                     or p.proowner <> b.proowner)) then
    raise exception 'post-check: another public function changed';
  end if;
  if (select count(*) from pg_proc where pronamespace = 'public'::regnamespace)
     <> (select count(*) from _s6ee_before) then
    raise exception 'post-check: number of public functions changed';
  end if;
  raise notice 'Step 6EE: all fail-closed checks passed. Committing.';
end $$;

-- behaviour: a verified recruiter looks at student X
do $$
declare rid uuid; t record; j jsonb; srv int; allavg int; nsub bigint; cfg uuid; tid uuid; pv_expected bigint;
begin
  -- data setup (no JWT yet = trusted, like a migration)
  select id into rid from public.recruiters limit 1;
  if rid is null then raise exception 'B: no recruiter row on staging'; end if;
  update public.recruiters set verified = true where id = rid;
  update public.student_profiles set status = 'active', profile_visibility = 'public' where id = '7d71bff4-1ec2-4778-b26d-9567a416bfac';
  update public.student_portfolios set is_public = true where student_id = '7d71bff4-1ec2-4778-b26d-9567a416bfac';
  select round(avg(communication_score) filter (where transcript_source = 'server'))::int,
         round(avg(communication_score))::int
    into srv, allavg from public.voice_explanations where student_id = '7d71bff4-1ec2-4778-b26d-9567a416bfac';
  -- one passed auto-graded submission, to prove stage69's count survives
  -- staging has no auto-graded task, so make one (all rolled back)
  insert into public.task_sandbox_config (language, test_cases, reference_solution) values ('python', '[{"id":"t1","stdin":"","expected_output":"1","visible":true,"weight":1}]'::jsonb, 'print(1)') returning id into cfg;
  update public.tasks set sandbox_config_id = cfg where id = (select id from public.tasks limit 1) returning id into tid;
  insert into public.task_submissions (student_id, task_id, sandbox_config_id, code, sandbox_score, status)
  values ('7d71bff4-1ec2-4778-b26d-9567a416bfac', tid, cfg, 'print(1)', 100, 'passed');
  select count(*) into nsub from public.task_submissions where student_id = '7d71bff4-1ec2-4778-b26d-9567a416bfac' and status = 'passed';
  if nsub < 1 then raise exception 'B: test setup made no passed submission'; end if;

  -- act as that recruiter, the way PostgREST would
  perform set_config('request.jwt.claims', json_build_object('sub', rid, 'role', 'authenticated')::text, true);
  if not public.is_verified_recruiter() then raise exception 'B: recruiter not verified in test'; end if;
  if not public.student_is_discoverable('7d71bff4-1ec2-4778-b26d-9567a416bfac') then raise exception 'B: student not discoverable in test'; end if;

  select * into t from public.recruiter_talent(_limit => 100) where student_id = '7d71bff4-1ec2-4778-b26d-9567a416bfac';
  if not found then
    raise exception 'B1: student missing from recruiter_talent (rows returned: %)',
      (select count(*) from public.recruiter_talent(_limit => 100)); end if;
  if t.comms_score is distinct from srv then
    raise exception 'B1: comms_score % (expected server-only average %; browser-inclusive average is %)', t.comms_score, srv, allavg; end if;
  select (select count(*) from public.proof_uploads pu where pu.student_id = '7d71bff4-1ec2-4778-b26d-9567a416bfac' and pu.status in ('Verified','verified')) + nsub
    into pv_expected;
  if t.proofs_verified <> pv_expected then
    raise exception 'B2: proofs_verified % (expected % = verified proofs + % passed submission(s)) - stage69 lost', t.proofs_verified, pv_expected, nsub; end if;
  if exists (select 1 from public.recruiter_talent(_min_comms => srv + 1) where student_id = '7d71bff4-1ec2-4778-b26d-9567a416bfac') then
    raise exception 'B3: _min_comms filter used a browser score'; end if;
  if not exists (select 1 from public.recruiter_talent(_min_comms => srv) where student_id = '7d71bff4-1ec2-4778-b26d-9567a416bfac') then
    raise exception 'B3b: _min_comms filter excluded a qualifying server score'; end if;

  j := public.recruiter_proof_profile('7d71bff4-1ec2-4778-b26d-9567a416bfac');
  if (j->>'communication')::int is distinct from srv then
    raise exception 'B4: profile communication % (expected %)', j->>'communication', srv; end if;
  if exists (select 1 from jsonb_array_elements(j->'explanations') e
              join public.voice_explanations v on v.id = (e->>'id')::uuid
             where v.transcript_source <> 'server') then
    raise exception 'B5: profile lists a non-server explanation'; end if;

  -- a non-recruiter gets nothing
  perform set_config('request.jwt.claims', json_build_object('sub', gen_random_uuid(), 'role', 'authenticated')::text, true);
  if exists (select 1 from public.recruiter_talent()) then raise exception 'B6: non-recruiter saw candidates'; end if;
  if (public.recruiter_proof_profile('7d71bff4-1ec2-4778-b26d-9567a416bfac') ? 'error') is not true then raise exception 'B7: non-recruiter saw a profile'; end if;

  raise notice 'Step 6EE behaviour: comms_score % = server-only average (browser-inclusive would be %), proofs_verified % includes % passed submission(s), filter and profile use server only, non-recruiter blocked. 7/7 passed.',
    srv, allavg, t.proofs_verified, nsub;
end $$;


set local lock_timeout = '5s';

do $$
declare v text;
begin

  -- both functions carry the expected rollback pre-check bodies (whitespace-normalised md5)
  select md5(btrim(regexp_replace(prosrc, '\s+', ' ', 'g'))) into v from pg_proc where oid = 'public.recruiter_talent(text, text[], text, integer, integer, integer, integer, integer)'::regprocedure;
  if v <> 'd3ec3dda80922a036fc3d39460ced541' then
    raise exception 'rollback pre-check: recruiter_talent body md5 is % (expected d3ec3dda80922a036fc3d39460ced541)', v;
  end if;
  select md5(btrim(regexp_replace(prosrc, '\s+', ' ', 'g'))) into v from pg_proc where oid = 'public.recruiter_proof_profile(uuid)'::regprocedure;
  if v <> '2d048797e2d64852834c65ef4d24170a' then
    raise exception 'rollback pre-check: recruiter_proof_profile body md5 is % (expected 2d048797e2d64852834c65ef4d24170a)', v;
  end if;
  raise notice 'Step 6EE rollback pre-check passed: the Step 6EE bodies are present.';
end $$;

create or replace function public.recruiter_talent(
  _role text default null, _skills text[] default null, _branch text default null,
  _min_skill integer default null, _min_comms integer default null,
  _active_within integer default null, _limit integer default 50, _offset integer default 0
)
returns table(
  student_id uuid, full_name text, branch text, batch text, target_role text,
  total_xp integer, trust_score numeric, skills_proven bigint, skills_total bigint,
  top_skills text[], lots_done bigint, proofs_verified bigint, comms_score integer,
  explanations bigint, days_since_active integer, active_weeks bigint,
  squad_name text, squad_rank integer, season_points integer, shortlisted boolean,
  total_matches bigint
)
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  with me as (select public.my_recruiter_id() as rid,
                     public.is_verified_recruiter() as ok),
  candidates as (
    select p.id, p.full_name, p.branch, p.batch, p.target_role,
           p.total_xp, p.trust_score, p.last_active
      from public.student_profiles p
     where (select ok from me)
       and public.student_is_discoverable(p.id)
       and (_branch is null or lower(p.branch) = lower(_branch))
       and (_role   is null or p.target_role ilike '%' || _role || '%')
       and (_active_within is null
            or (p.last_active is not null
                and p.last_active >= now() - make_interval(days => _active_within)))
  ),
  enriched as (
    select c.*,
           (select count(*) from public.student_skills s
             where s.student_id = c.id and s.status = 'proven') as skills_proven,
           (select count(*) from public.student_skills s
             where s.student_id = c.id) as skills_total,
           (select coalesce(array_agg(s.skill order by
                      array_position(array['proven','assessed','claimed'], s.status), s.skill),
                    '{}')
              from public.student_skills s where s.student_id = c.id) as top_skills,
           (select max(s.assessed_score) from public.student_skills s
             where s.student_id = c.id) as best_skill_score,
           (select count(*) from public.tasks t
             where t.student_id = c.id and t.status in ('Completed','completed')) as lots_done,
           -- CHANGED (stage69): verified proofs + passed auto-graded submissions.
           (select count(*) from public.proof_uploads pu
             where pu.student_id = c.id and pu.status in ('Verified','verified'))
           + (select count(*) from public.task_submissions ts
             where ts.student_id = c.id and ts.status = 'passed') as proofs_verified,
           (select round(avg(v.communication_score))::integer from public.voice_explanations v
             where v.student_id = c.id and v.communication_score is not null) as comms_score,
           (select count(*) from public.voice_explanations v
             where v.student_id = c.id) as explanations,
           (select count(distinct w.week) from public.student_weekly_scores w
             where w.student_id = c.id and w.points > 0) as active_weeks,
           (select q.name from public.squad_members m
              join public.squads q on q.id = m.squad_id
             where m.student_id = c.id and m.left_at is null limit 1) as squad_name,
           (select q.rank from public.squad_members m
              join public.squads q on q.id = m.squad_id
             where m.student_id = c.id and m.left_at is null limit 1) as squad_rank,
           (select q.points from public.squad_members m
              join public.squads q on q.id = m.squad_id
             where m.student_id = c.id and m.left_at is null limit 1) as season_points,
           exists (select 1 from public.recruiter_shortlists sl
                    where sl.student_id = c.id
                      and sl.recruiter_id = (select rid from me)) as shortlisted
      from candidates c
  ),
  filtered as (
    select * from enriched e
     where (_min_skill is null or coalesce(e.best_skill_score, 0) >= _min_skill)
       and (_min_comms is null or coalesce(e.comms_score, 0)     >= _min_comms)
       and (_skills is null or exists (
              select 1 from public.student_skills s
               where s.student_id = e.id
                 and lower(s.skill) = any (select lower(x) from unnest(_skills) x)))
  )
  select f.id, f.full_name, f.branch, f.batch, f.target_role,
         f.total_xp, f.trust_score,
         f.skills_proven, f.skills_total, f.top_skills,
         f.lots_done, f.proofs_verified,
         f.comms_score, f.explanations,
         case when f.last_active is null then 999
              else (current_date - f.last_active::date) end,
         f.active_weeks,
         f.squad_name, f.squad_rank, f.season_points,
         f.shortlisted,
         count(*) over ()
    from filtered f
   order by f.skills_proven desc, f.proofs_verified desc, f.total_xp desc
   limit greatest(1, least(coalesce(_limit, 50), 100))
  offset greatest(0, coalesce(_offset, 0));
$$;

create or replace function public.recruiter_proof_profile(_student_id uuid)
returns jsonb language plpgsql stable security definer set search_path = public, pg_temp as $fn$
declare p record; rid uuid := public.my_recruiter_id(); accepted boolean;
begin
  if not public.is_verified_recruiter() then
    return jsonb_build_object('error', 'Your recruiter account is awaiting verification.');
  end if;

  if not public.student_is_discoverable(_student_id) then
    -- Deliberately the same answer as "no such student": whether a particular
    -- person is on this platform is itself something they did not consent to
    -- share.
    return jsonb_build_object('error', 'No candidate found.');
  end if;

  select * into p from public.student_profiles where id = _student_id;

  select sl.student_response = 'accepted' into accepted
    from public.recruiter_shortlists sl
   where sl.recruiter_id = rid and sl.student_id = _student_id;

  return jsonb_build_object(
    'id', p.id,
    'full_name', p.full_name,
    'branch', p.branch,
    'batch', p.batch,
    'year_of_study', p.year_of_study,
    'target_role', p.target_role,
    'secondary_roles', p.secondary_roles,
    'work_preference', p.work_preference,
    'preferred_locations', p.preferred_locations,
    'open_to_relocate', p.open_to_relocate,
    'total_xp', p.total_xp,
    'trust_score', p.trust_score,
    'last_active', p.last_active,
    'days_since_active', case when p.last_active is null then 999
                              else (current_date - p.last_active::date) end,

    'contact_unlocked', coalesce(accepted, false),
    'contact', case when coalesce(accepted, false) then
        (select jsonb_build_object('email', c.email, 'phone', c.phone,
                                   'github', c.github_url, 'linkedin', c.linkedin_url)
           from public.student_contact c where c.student_id = p.id)
      else null end,

    'skills', (select coalesce(jsonb_agg(jsonb_build_object(
                 'skill', s.skill, 'status', s.status, 'score', s.assessed_score,
                 'lots', s.proven_lots, 'explanations', s.proven_voice,
                 'last_evidence_at', s.last_evidence_at)
                 order by array_position(array['proven','assessed','claimed','needs_improvement'],
                                         s.status), s.skill), '[]'::jsonb)
                 from public.student_skills s where s.student_id = p.id),

    'certifications', (select coalesce(jsonb_agg(jsonb_build_object(
                         'name', t.name, 'issuer', t.issuer, 'issued_on', t.issued_on,
                         'url', t.credential_url, 'source', t.source)
                         order by t.issued_on desc nulls last), '[]'::jsonb)
                         from public.student_certifications t where t.student_id = p.id),

    'scorecard', (select jsonb_build_object(
                    'resume_quality', s.resume_quality_score,
                    'ats_match', s.ats_match_score,
                    'skill_proof', s.skill_proof_score,
                    'project_proof', s.project_proof_score,
                    'reasoning', s.reasoning_score,
                    'coding', s.coding_score,
                    'interview_readiness', s.interview_readiness_score,
                    'skill_gap', s.skill_gap,
                    'at', s.created_at)
                    from public.resume_scorecards s
                   where s.student_id = p.id order by s.created_at desc limit 1),

    'work', (select coalesce(jsonb_agg(w order by w.submitted_at desc), '[]'::jsonb) from (
        select pu.id, pu.status, pu.ai_score, pu.submitted_at,
               (select t.title from public.tasks t where t.id = pu.task_id) as title,
               (select t.difficulty from public.tasks t where t.id = pu.task_id) as difficulty
          from public.proof_uploads pu
         where pu.student_id = p.id and pu.is_public = true
         order by pu.submitted_at desc nulls last limit 10) w),

    'explanations', (select coalesce(jsonb_agg(v order by v.created_at desc), '[]'::jsonb) from (
        select ve.id, ve.duration_seconds, ve.communication_score,
               ve.communication_notes, ve.created_at,
               (select t.title from public.tasks t where t.id = ve.task_id) as about
          from public.voice_explanations ve
         where ve.student_id = p.id and ve.communication_score is not null
         order by ve.created_at desc limit 5) v),

    'communication', (select round(avg(v.communication_score))::integer
                        from public.voice_explanations v
                       where v.student_id = p.id and v.communication_score is not null),

    -- Consistency as weeks actually turned up, not a streak a single good
    -- fortnight can inflate.
    'consistency', jsonb_build_object(
      'active_weeks', (select count(*) from public.student_weekly_scores w
                        where w.student_id = p.id and w.points > 0),
      'weeks_total',  (select count(distinct w.week) from public.student_weekly_scores w
                        where w.student_id = p.id),
      'current_streak', (select current_days from public.student_streaks st
                          where st.student_id = p.id),
      'lots_done', (select count(*) from public.tasks t
                     where t.student_id = p.id and t.status in ('Completed','completed'))),

    'squad', (select jsonb_build_object(
                'name', q.name, 'rank', q.rank, 'points', q.points,
                'record', q.wins || '-' || q.draws || '-' || q.losses,
                'contribution', m.contribution)
                from public.squad_members m
                join public.squads q on q.id = m.squad_id
               where m.student_id = p.id and m.left_at is null limit 1),

    'ladder', jsonb_build_object(
      'track', (select t.track_slug from public.student_tracks t
                 where t.student_id = p.id order by t.created_at desc limit 1),
      'cleared', (select count(*) from public.student_levels sl
                   where sl.student_id = p.id and sl.status in ('cleared','mastered'))),

    'shortlist', (select jsonb_build_object('stage', sl.stage,
                          'response', sl.student_response, 'note', sl.note)
                    from public.recruiter_shortlists sl
                   where sl.recruiter_id = rid and sl.student_id = p.id)
  );
end $fn$;

do $$
declare v text;
begin

  -- both functions carry the expected rollback post-check bodies (whitespace-normalised md5)
  select md5(btrim(regexp_replace(prosrc, '\s+', ' ', 'g'))) into v from pg_proc where oid = 'public.recruiter_talent(text, text[], text, integer, integer, integer, integer, integer)'::regprocedure;
  if v <> 'f7c1eef2f57c8d5b1f961ea76a661fda' then
    raise exception 'rollback post-check: recruiter_talent body md5 is % (expected f7c1eef2f57c8d5b1f961ea76a661fda)', v;
  end if;
  select md5(btrim(regexp_replace(prosrc, '\s+', ' ', 'g'))) into v from pg_proc where oid = 'public.recruiter_proof_profile(uuid)'::regprocedure;
  if v <> 'b467d6f7769c61887d854fb4358cd30e' then
    raise exception 'rollback post-check: recruiter_proof_profile body md5 is % (expected b467d6f7769c61887d854fb4358cd30e)', v;
  end if;
  if has_function_privilege('anon', 'public.recruiter_talent(text, text[], text, integer, integer, integer, integer, integer)'::regprocedure, 'EXECUTE')
     or not has_function_privilege('authenticated', 'public.recruiter_talent(text, text[], text, integer, integer, integer, integer, integer)'::regprocedure, 'EXECUTE') then
    raise exception 'rollback post-check: grants on recruiter_talent unexpected';
  end if;
  raise notice 'Step 6EE rollback: bodies restored to stage69 / stage35c. Committing.';
end $$;

rollback;
