-- Step 6EE: production execution of migration 46 (recruiter provenance filter).
--
-- PREPARED, NOT APPLIED. Run only after the project owner's explicit approval,
-- manually in Cloud SQL Studio on prooflab-db / database prooflab, as the
-- owner of recruiter_talent and recruiter_proof_profile (expected prooflab_app).
-- Run step6ee-migration-46-production-prereq-readonly.sql FIRST.
--
-- What it does: a recruiter only sees, and filters on, communication scores
-- from explanations with transcript_source = 'server'. No table, row or
-- column is changed. Two functions are replaced.
--
-- DO NOT run migration/46-recruiter-provenance-filter.sql in production:
-- it was written from stage35c's recruiter_talent and would silently undo
-- stage69 (passed auto-graded task_submissions counted in proofs_verified).
-- This script applies the same filter to the CURRENT bodies instead:
--   recruiter_talent        = exported production body + filter (1 place)
--   recruiter_proof_profile = exported production body + filter (2 places)
--   (migration/step6ee-production-before/*.sql: pg_get_functiondef output exported by
--   the owner 2026-09-28; executable SQL identical to stage69 / stage35c, only
--   comments differ. Business logic and comments are kept unchanged.)
-- Generated by scripts/dev-tools/step6ee_build.py (reviewers can re-run it
-- and diff: the bodies come from migration/step6ee-production-before/).
--
-- Fingerprints (md5 of the body with all whitespace runs collapsed to one space):
--   before: recruiter_talent b47030abb6be083cb964efa247e98eb6  recruiter_proof_profile 642189a0d9c35aaeeabf4a622037194a
--   after:  recruiter_talent 66d86705e34347c53d759b533dbca3c9  recruiter_proof_profile 95a23fd33dd0252b70492dfd31fc7818
--   (original, regressing 46 talent body: a8a046d776b01dd5160ef1870487b578)
--
-- Additions beyond the original 46:
--   - pre-checks (exact current bodies, signatures, return types, ownership,
--     not already applied, referenced objects exist)
--   - EXECUTE: revoke from PUBLIC and anon, grant to authenticated (stage35c's
--     intended grants; staging was found with PUBLIC and anon EXECUTE)
--   - post-checks before COMMIT, including "no other public function changed"
--   - lock_timeout 5s; one transaction

begin;

set local lock_timeout = '5s';

do $$
declare v text;
begin
  -- exactly one of each, with the expected signatures and return types
  if (select count(*) from pg_proc where pronamespace = 'public'::regnamespace and proname = 'recruiter_talent') <> 1
     or (select count(*) from pg_proc where pronamespace = 'public'::regnamespace and proname = 'recruiter_proof_profile') <> 1 then
    raise exception 'pre-check: expected exactly one recruiter_talent and one recruiter_proof_profile';
  end if;
  if to_regprocedure('public.recruiter_talent(text, text[], text, integer, integer, integer, integer, integer)') is null or to_regprocedure('public.recruiter_proof_profile(uuid)') is null then
    raise exception 'pre-check: recruiter_talent / recruiter_proof_profile signature not found';
  end if;
  if pg_get_function_result('public.recruiter_talent(text, text[], text, integer, integer, integer, integer, integer)'::regprocedure) <> 'TABLE(student_id uuid, full_name text, branch text, batch text, target_role text, total_xp integer, trust_score numeric, skills_proven bigint, skills_total bigint, top_skills text[], lots_done bigint, proofs_verified bigint, comms_score integer, explanations bigint, days_since_active integer, active_weeks bigint, squad_name text, squad_rank integer, season_points integer, shortlisted boolean, total_matches bigint)' then
    raise exception 'pre-check: recruiter_talent return type differs: %', pg_get_function_result('public.recruiter_talent(text, text[], text, integer, integer, integer, integer, integer)'::regprocedure);
  end if;
  if pg_get_function_result('public.recruiter_proof_profile(uuid)'::regprocedure) <> 'jsonb' then
    raise exception 'pre-check: recruiter_proof_profile does not return jsonb';
  end if;

  -- already applied? (either the original 46 body or this one)
  if (select position('transcript_source' in prosrc) from pg_proc where oid = 'public.recruiter_talent(text, text[], text, integer, integer, integer, integer, integer)'::regprocedure) > 0
     or (select position('transcript_source' in prosrc) from pg_proc where oid = 'public.recruiter_proof_profile(uuid)'::regprocedure) > 0 then
    raise exception 'pre-check: a transcript_source filter is already present - migration 46 (or a version of it) is already applied; refusing';
  end if;

  -- both functions carry the expected pre-check bodies (whitespace-normalised md5)
  select md5(btrim(regexp_replace(prosrc, '\s+', ' ', 'g'))) into v from pg_proc where oid = 'public.recruiter_talent(text, text[], text, integer, integer, integer, integer, integer)'::regprocedure;
  if v <> 'b47030abb6be083cb964efa247e98eb6' then
    raise exception 'pre-check: recruiter_talent body md5 is % (expected b47030abb6be083cb964efa247e98eb6)', v;
  end if;
  select md5(btrim(regexp_replace(prosrc, '\s+', ' ', 'g'))) into v from pg_proc where oid = 'public.recruiter_proof_profile(uuid)'::regprocedure;
  if v <> '642189a0d9c35aaeeabf4a622037194a' then
    raise exception 'pre-check: recruiter_proof_profile body md5 is % (expected 642189a0d9c35aaeeabf4a622037194a)', v;
  end if;

  -- CREATE OR REPLACE keeps the owner; only the owner (or a member) may replace
  if not pg_has_role(current_user, (select proowner from pg_proc where oid = 'public.recruiter_talent(text, text[], text, integer, integer, integer, integer, integer)'::regprocedure), 'MEMBER')
     or not pg_has_role(current_user, (select proowner from pg_proc where oid = 'public.recruiter_proof_profile(uuid)'::regprocedure), 'MEMBER') then
    raise exception 'pre-check: % does not own recruiter_talent / recruiter_proof_profile', current_user;
  end if;

  -- objects the new bodies read must exist
  if not exists (select 1 from information_schema.columns where table_schema = 'public'
                  and table_name = 'voice_explanations' and column_name = 'transcript_source') then
    raise exception 'pre-check: voice_explanations.transcript_source missing';
  end if;
  if not exists (select 1 from pg_constraint where conrelid = 'public.voice_explanations'::regclass
                  and contype = 'c' and pg_get_constraintdef(oid) like '%transcript_source%'
                  and pg_get_constraintdef(oid) like '%''server''%') then
    raise exception 'pre-check: no CHECK on voice_explanations.transcript_source allowing ''server''';
  end if;
  if to_regclass('public.task_submissions') is null then
    raise exception 'pre-check: task_submissions (stage69) missing';
  end if;
  if to_regprocedure('public.my_recruiter_id()') is null or to_regprocedure('public.is_verified_recruiter()') is null
     or to_regprocedure('public.student_is_discoverable(uuid)') is null then
    raise exception 'pre-check: recruiter helper functions missing';
  end if;
  raise notice 'Step 6EE pre-checks passed: current bodies are the exported production pre-46 bodies.';
end $$;

-- snapshot every public function (body + ACL + owner) to prove afterwards
-- that only the two intended functions changed
create temp table _s6ee_before on commit drop as
  select p.oid, p.proname, md5(p.prosrc) as src_md5, p.proacl::text as acl, p.proowner,
         p.prosecdef, p.proconfig
    from pg_proc p where p.pronamespace = 'public'::regnamespace;

CREATE OR REPLACE FUNCTION public.recruiter_talent(_role text DEFAULT NULL::text, _skills text[] DEFAULT NULL::text[], _branch text DEFAULT NULL::text, _min_skill integer DEFAULT NULL::integer, _min_comms integer DEFAULT NULL::integer, _active_within integer DEFAULT NULL::integer, _limit integer DEFAULT 50, _offset integer DEFAULT 0)
 RETURNS TABLE(student_id uuid, full_name text, branch text, batch text, target_role text, total_xp integer, trust_score numeric, skills_proven bigint, skills_total bigint, top_skills text[], lots_done bigint, proofs_verified bigint, comms_score integer, explanations bigint, days_since_active integer, active_weeks bigint, squad_name text, squad_rank integer, season_points integer, shortlisted boolean, total_matches bigint)
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public', 'pg_temp'
AS $function$
  with me as (select public.my_recruiter_id() as rid,
                     public.is_verified_recruiter() as ok),
  candidates as (
    select p.id, p.full_name, p.branch, p.batch, p.target_role,
           p.total_xp, p.trust_score, p.last_active
      from public.student_profiles p
     where (select ok from me)
       and public.student_is_discoverable(p.id)
       and (_branch is null or lower(p.branch) = lower(_branch))
       and (_role   is null or p.target_role ilike '%' || _role || '%')
       and (_active_within is null
            or (p.last_active is not null
                and p.last_active >= now() - make_interval(days => _active_within)))
  ),
  enriched as (
    select c.*,
           (select count(*) from public.student_skills s
             where s.student_id = c.id and s.status = 'proven') as skills_proven,
           (select count(*) from public.student_skills s
             where s.student_id = c.id) as skills_total,
           (select coalesce(array_agg(s.skill order by
                      array_position(array['proven','assessed','claimed'], s.status), s.skill),
                    '{}')
              from public.student_skills s where s.student_id = c.id) as top_skills,
           (select max(s.assessed_score) from public.student_skills s
             where s.student_id = c.id) as best_skill_score,
           (select count(*) from public.tasks t
             where t.student_id = c.id and t.status in ('Completed','completed')) as lots_done,
           (select count(*) from public.proof_uploads pu
             where pu.student_id = c.id and pu.status in ('Verified','verified'))
           + (select count(*) from public.task_submissions ts
             where ts.student_id = c.id and ts.status = 'passed') as proofs_verified,
           (select round(avg(v.communication_score))::integer from public.voice_explanations v
             where v.student_id = c.id and v.communication_score is not null
               -- Step 6H/6EE: only a server-transcribed explanation counts
               -- toward the score a recruiter sees and filters on.
               and v.transcript_source = 'server') as comms_score,
           (select count(*) from public.voice_explanations v
             where v.student_id = c.id) as explanations,
           (select count(distinct w.week) from public.student_weekly_scores w
             where w.student_id = c.id and w.points > 0) as active_weeks,
           (select q.name from public.squad_members m
              join public.squads q on q.id = m.squad_id
             where m.student_id = c.id and m.left_at is null limit 1) as squad_name,
           (select q.rank from public.squad_members m
              join public.squads q on q.id = m.squad_id
             where m.student_id = c.id and m.left_at is null limit 1) as squad_rank,
           (select q.points from public.squad_members m
              join public.squads q on q.id = m.squad_id
             where m.student_id = c.id and m.left_at is null limit 1) as season_points,
           exists (select 1 from public.recruiter_shortlists sl
                    where sl.student_id = c.id
                      and sl.recruiter_id = (select rid from me)) as shortlisted
      from candidates c
  ),
  filtered as (
    select * from enriched e
     where (_min_skill is null or coalesce(e.best_skill_score, 0) >= _min_skill)
       and (_min_comms is null or coalesce(e.comms_score, 0)     >= _min_comms)
       and (_skills is null or exists (
              select 1 from public.student_skills s
               where s.student_id = e.id
                 and lower(s.skill) = any (select lower(x) from unnest(_skills) x)))
  )
  select f.id, f.full_name, f.branch, f.batch, f.target_role,
         f.total_xp, f.trust_score,
         f.skills_proven, f.skills_total, f.top_skills,
         f.lots_done, f.proofs_verified,
         f.comms_score, f.explanations,
         case when f.last_active is null then 999
              else (current_date - f.last_active::date) end,
         f.active_weeks,
         f.squad_name, f.squad_rank, f.season_points,
         f.shortlisted,
         count(*) over ()
    from filtered f
   order by f.skills_proven desc, f.proofs_verified desc, f.total_xp desc
   limit greatest(1, least(coalesce(_limit, 50), 100))
  offset greatest(0, coalesce(_offset, 0));
$function$;

CREATE OR REPLACE FUNCTION public.recruiter_proof_profile(_student_id uuid)
 RETURNS jsonb
 LANGUAGE plpgsql
 STABLE SECURITY DEFINER
 SET search_path TO 'public', 'pg_temp'
AS $function$
declare p record; rid uuid := public.my_recruiter_id(); accepted boolean;
begin
  if not public.is_verified_recruiter() then
    return jsonb_build_object('error', 'Your recruiter account is awaiting verification.');
  end if;

  if not public.student_is_discoverable(_student_id) then
    -- Deliberately the same answer as "no such student": whether a particular
    -- person is on the platform is itself something they did not consent to
    -- share.
    return jsonb_build_object('error', 'No candidate found.');
  end if;

  select * into p from public.student_profiles where id = _student_id;

  select sl.student_response = 'accepted' into accepted
    from public.recruiter_shortlists sl
   where sl.recruiter_id = rid and sl.student_id = _student_id;

  return jsonb_build_object(
    'id', p.id,
    'full_name', p.full_name,
    'branch', p.branch,
    'batch', p.batch,
    'year_of_study', p.year_of_study,
    'target_role', p.target_role,
    'secondary_roles', p.secondary_roles,
    'work_preference', p.work_preference,
    'preferred_locations', p.preferred_locations,
    'open_to_relocate', p.open_to_relocate,
    'total_xp', p.total_xp,
    'trust_score', p.trust_score,
    'last_active', p.last_active,
    'days_since_active', case when p.last_active is null then 999
                              else (current_date - p.last_active::date) end,

    -- Contact details are the one thing a shortlist buys, and only if the
    -- student said yes.
    'contact_unlocked', coalesce(accepted, false),
    'contact', case when coalesce(accepted, false) then
        (select jsonb_build_object('email', c.email, 'phone', c.phone,
                                   'github', c.github_url, 'linkedin', c.linkedin_url)
           from public.student_contact c where c.student_id = p.id)
      else null end,

    -- Skills, each with what earned the status rather than only the label.
    'skills', (select coalesce(jsonb_agg(jsonb_build_object(
                 'skill', s.skill, 'status', s.status, 'score', s.assessed_score,
                 'lots', s.proven_lots, 'explanations', s.proven_voice,
                 'last_evidence_at', s.last_evidence_at)
                 order by array_position(array['proven','assessed','claimed','needs_improvement'],
                                         s.status), s.skill), '[]'::jsonb)
                 from public.student_skills s where s.student_id = p.id),

    'certifications', (select coalesce(jsonb_agg(jsonb_build_object(
                         'name', t.name, 'issuer', t.issuer, 'issued_on', t.issued_on,
                         'url', t.credential_url, 'source', t.source)
                         order by t.issued_on desc nulls last), '[]'::jsonb)
                         from public.student_certifications t where t.student_id = p.id),

    'scorecard', (select jsonb_build_object(
                    'resume_quality', s.resume_quality_score,
                    'ats_match', s.ats_match_score,
                    'skill_proof', s.skill_proof_score,
                    'project_proof', s.project_proof_score,
                    'reasoning', s.reasoning_score,
                    'coding', s.coding_score,
                    'interview_readiness', s.interview_readiness_score,
                    'skill_gap', s.skill_gap,
                    'at', s.created_at)
                    from public.resume_scorecards s
                   where s.student_id = p.id order by s.created_at desc limit 1),

    -- The work itself, which is what a score is a summary of.
    'work', (select coalesce(jsonb_agg(w order by w.submitted_at desc), '[]'::jsonb) from (
        select pu.id, pu.status, pu.ai_score, pu.submitted_at,
               (select t.title from public.tasks t where t.id = pu.task_id) as title,
               (select t.difficulty from public.tasks t where t.id = pu.task_id) as difficulty
          from public.proof_uploads pu
         where pu.student_id = p.id and pu.is_public = true
         order by pu.submitted_at desc nulls last limit 10) w),

    'explanations', (select coalesce(jsonb_agg(v order by v.created_at desc), '[]'::jsonb) from (
        select ve.id, ve.duration_seconds, ve.communication_score,
               ve.communication_notes, ve.created_at,
               (select t.title from public.tasks t where t.id = ve.task_id) as about
          from public.voice_explanations ve
         where ve.student_id = p.id and ve.communication_score is not null
           -- Step 6H/6EE: same provenance gate as recruiter_talent.comms_score
           and ve.transcript_source = 'server'
         order by ve.created_at desc limit 5) v),

    'communication', (select round(avg(v.communication_score))::integer
                        from public.voice_explanations v
                       where v.student_id = p.id and v.communication_score is not null
                         and v.transcript_source = 'server'),

    -- Consistency: how many weeks they actually turned up, not a streak number
    -- that a single good fortnight can inflate.
    'consistency', jsonb_build_object(
      'active_weeks', (select count(*) from public.student_weekly_scores w
                        where w.student_id = p.id and w.points > 0),
      'weeks_total',  (select count(distinct w.week) from public.student_weekly_scores w
                        where w.student_id = p.id),
      'current_streak', (select current_days from public.student_streaks st
                          where st.student_id = p.id),
      'lots_done', (select count(*) from public.tasks t
                     where t.student_id = p.id and t.status in ('Completed','completed'))),

    'squad', (select jsonb_build_object(
                'name', q.name, 'rank', q.rank, 'points', q.points,
                'record', q.wins || '-' || q.draws || '-' || q.losses,
                'contribution', m.contribution)
                from public.squad_members m
                join public.squads q on q.id = m.squad_id
               where m.student_id = p.id and m.left_at is null limit 1),

    'ladder', jsonb_build_object(
      'track', (select t.track_slug from public.student_tracks t
                 where t.student_id = p.id order by t.created_at desc limit 1),
      'cleared', (select count(*) from public.student_levels sl
                   where sl.student_id = p.id and sl.status in ('cleared','mastered'))),

    'shortlist', (select jsonb_build_object('stage', sl.stage,
                          'response', sl.student_response, 'note', sl.note)
                    from public.recruiter_shortlists sl
                   where sl.recruiter_id = rid and sl.student_id = p.id)
  );
end $function$;

-- permissions: recruiter-facing, so signed-in users only (stage35c's intent:
-- revoke from public, anon; grant to authenticated). Both functions check
-- is_verified_recruiter() themselves.
revoke execute on function public.recruiter_talent(text, text[], text, integer, integer, integer, integer, integer), public.recruiter_proof_profile(uuid) from public, anon;
grant execute on function public.recruiter_talent(text, text[], text, integer, integer, integer, integer, integer), public.recruiter_proof_profile(uuid) to authenticated;

do $$
declare v text; r record;
begin

  -- both functions carry the expected post-check bodies (whitespace-normalised md5)
  select md5(btrim(regexp_replace(prosrc, '\s+', ' ', 'g'))) into v from pg_proc where oid = 'public.recruiter_talent(text, text[], text, integer, integer, integer, integer, integer)'::regprocedure;
  if v <> '66d86705e34347c53d759b533dbca3c9' then
    raise exception 'post-check: recruiter_talent body md5 is % (expected 66d86705e34347c53d759b533dbca3c9)', v;
  end if;
  select md5(btrim(regexp_replace(prosrc, '\s+', ' ', 'g'))) into v from pg_proc where oid = 'public.recruiter_proof_profile(uuid)'::regprocedure;
  if v <> '95a23fd33dd0252b70492dfd31fc7818' then
    raise exception 'post-check: recruiter_proof_profile body md5 is % (expected 95a23fd33dd0252b70492dfd31fc7818)', v;
  end if;
  if (select position('task_submissions' in prosrc) from pg_proc where oid = 'public.recruiter_talent(text, text[], text, integer, integer, integer, integer, integer)'::regprocedure) = 0 then
    raise exception 'post-check: stage69 task_submissions count lost from recruiter_talent';
  end if;
  if pg_get_function_result('public.recruiter_talent(text, text[], text, integer, integer, integer, integer, integer)'::regprocedure) <> 'TABLE(student_id uuid, full_name text, branch text, batch text, target_role text, total_xp integer, trust_score numeric, skills_proven bigint, skills_total bigint, top_skills text[], lots_done bigint, proofs_verified bigint, comms_score integer, explanations bigint, days_since_active integer, active_weeks bigint, squad_name text, squad_rank integer, season_points integer, shortlisted boolean, total_matches bigint)'
     or pg_get_function_result('public.recruiter_proof_profile(uuid)'::regprocedure) <> 'jsonb' then
    raise exception 'post-check: return type changed';
  end if;

  for r in select p.oid, p.proname, p.prosecdef, p.proconfig, p.proowner, p.proacl, b.proowner as old_owner
             from pg_proc p join _s6ee_before b on b.oid = p.oid
            where p.oid in ('public.recruiter_talent(text, text[], text, integer, integer, integer, integer, integer)'::regprocedure, 'public.recruiter_proof_profile(uuid)'::regprocedure) loop
    if not r.prosecdef then raise exception 'post-check: % not SECURITY DEFINER', r.proname; end if;
    if r.proconfig is null or not ('search_path=public, pg_temp' = any (r.proconfig)) then
      raise exception 'post-check: % search_path not pinned (%)', r.proname, r.proconfig;
    end if;
    if r.proowner <> r.old_owner then raise exception 'post-check: % owner changed', r.proname; end if;
    if not has_function_privilege('authenticated', r.oid, 'EXECUTE') then
      raise exception 'post-check: authenticated lost EXECUTE on %', r.proname; end if;
    if has_function_privilege('anon', r.oid, 'EXECUTE') then
      raise exception 'post-check: anon can EXECUTE %', r.proname; end if;
    if exists (select 1 from aclexplode(coalesce(r.proacl, acldefault('f', r.proowner))) a where a.grantee = 0) then
      raise exception 'post-check: PUBLIC can EXECUTE %', r.proname; end if;
  end loop;

  -- nothing else changed: every other public function identical, none added or removed
  if exists (select 1 from _s6ee_before b join pg_proc p on p.oid = b.oid
              where b.oid not in ('public.recruiter_talent(text, text[], text, integer, integer, integer, integer, integer)'::regprocedure, 'public.recruiter_proof_profile(uuid)'::regprocedure)
                and (md5(p.prosrc) <> b.src_md5 or p.proacl::text is distinct from b.acl
                     or p.proowner <> b.proowner)) then
    raise exception 'post-check: another public function changed';
  end if;
  if (select count(*) from pg_proc where pronamespace = 'public'::regnamespace)
     <> (select count(*) from _s6ee_before) then
    raise exception 'post-check: number of public functions changed';
  end if;
  raise notice 'Step 6EE: all fail-closed checks passed. Committing.';
end $$;

commit;
notify pgrst, 'reload schema';
