-- GENERATED by scripts/dev-tools/step6dd_build_rehearsal.py - do not edit.
-- Staging rehearsal of step6dd-migration-45-production-execution.sql in a
-- throwaway schema. Always ends in ROLLBACK.
-- Step 6DD: production execution of migration 45, self-contained.
--
-- PREPARED, NOT APPLIED. Run only after the project owner's explicit
-- approval for this one change, manually via Cloud SQL Studio on
-- prooflab-db / database prooflab, connected as prooflab_app.
--
-- What 45 does (see migration/45-voice-scoring-lease-token.sql):
--   - adds voice_explanations.scoring_lease_token uuid
--   - DROPS migration 44's claim_voice_scoring(uuid, integer) -> boolean
--     and recreates it as -> table(claimed boolean, lease_token uuid)
--     (Postgres cannot change a function's return type in place)
--   - adds complete_voice_scoring(uuid, uuid, integer, text) -> boolean
--   - adds fail_voice_scoring(uuid, uuid, text) -> boolean
--   - locks all three down to service_role only
--
-- Dependency on 44: 45 REPLACES 44's function and uses 44's column
-- (scoring_claimed_at). It must only ever run on a database whose
-- claim_voice_scoring is exactly 44's boolean shape. The pre-check below
-- enforces that, so:
--   - on a database without 44          -> aborts, nothing changed
--   - on a database already carrying 45 -> aborts, nothing changed
--     (this is what keeps a mistaken re-run, or a run against staging,
--     from dropping and recreating an existing 45 function)
--
-- The DROP in 45 is deliberate and safe here ONLY because the pre-check
-- has already proven the thing being dropped is 44's boolean version.
--
-- Differences from the original migration file, all additive:
--   1. set local lock_timeout: ALTER TABLE needs a brief ACCESS EXCLUSIVE
--      lock on voice_explanations. Without a timeout it could queue behind
--      a long transaction and block every voice read/write while it waits.
--      With it, the script aborts after 5 s instead (nothing changed).
--   2. pre-checks and fail-closed post-checks, INSIDE the transaction,
--      BEFORE COMMIT (a post-commit check cannot undo anything).
--   3. the original's own begin/commit/notify are removed; one outer
--      transaction wraps everything.
--   4. FOUR deliberate logic fixes (Step 6DD final audit, 2026-09-28),
--      each reproduced against the original statements on staging in a
--      rolled-back throwaway schema:
--        a. fail_voice_scoring: a late or repeated fail with the token that
--           just saved a score turned 'scored' into 'failed' (complete
--           keeps the token). Now requires status <> 'scored'.
--        b. complete_voice_scoring: a repeated complete with the same token
--           overwrote the saved score. Now requires status <> 'scored'.
--        c. claim_voice_scoring: a null / 0 / negative TTL made a live
--           claim look stale, so a second caller could take it over. Now
--           raises unless TTL >= 1.
--        d. complete_voice_scoring: accepted any integer or null as the
--           score. voice-score grades 0-100 and clamps to that range; the
--           column has no CHECK. Now raises unless 0 <= score <= 100.
--      Post-checks below refuse to COMMIT if any of the four is missing.
--   5. pre-check: voice_explanations must NOT have FORCE ROW LEVEL
--      SECURITY. These SECURITY DEFINER functions run as the table owner,
--      which bypasses RLS only while FORCE is off; with FORCE on (and no
--      UPDATE policy) every claim/complete/fail would silently update 0
--      rows.
-- Every other DDL statement is copied verbatim from
-- migration/45-voice-scoring-lease-token.sql. That file (and staging,
-- which ran it) still carries the UNFIXED version: never run it in
-- production. Undo script: step6dd-migration-45-rollback.sql.

begin;

-- throwaway copy of the objects migration 45 touches, in the
-- "migration 44 applied" state. Everything below is rolled back.
create schema s6dd_rehearsal;
create table s6dd_rehearsal.voice_explanations (
  id uuid primary key,
  status text not null default 'recorded'
    check (status in ('recorded', 'scored', 'failed')),
  transcript text,
  communication_score integer,
  communication_notes text,
  scoring_claimed_at timestamptz
);
alter table s6dd_rehearsal.voice_explanations enable row level security;
-- same column protection trigger production has (stage6)
create trigger protect_voice_explanations before update on s6dd_rehearsal.voice_explanations
  for each row execute function public.protect_columns(
    'communication_score', 'communication_notes', 'status', 'transcript');
grant select, insert, update, delete on s6dd_rehearsal.voice_explanations to service_role;
create function s6dd_rehearsal.guard_voice_explanations_insert() returns trigger
  language plpgsql as $f$ begin return new; end $f$;

-- migration 44's function, exactly as 44 creates it (schema moved)
create or replace function s6dd_rehearsal.claim_voice_scoring(_id uuid, _claim_ttl_seconds integer default 120)
returns boolean
language plpgsql
security definer
set search_path to 's6dd_rehearsal', 'pg_temp'
as $function$
declare n integer;
begin
  update s6dd_rehearsal.voice_explanations
     set scoring_claimed_at = now()
   where id = _id
     and status <> 'scored'
     and (scoring_claimed_at is null
          or scoring_claimed_at < now() - make_interval(secs => _claim_ttl_seconds));
  get diagnostics n = row_count;
  return n > 0;
end $function$;
revoke all on function s6dd_rehearsal.claim_voice_scoring(uuid, integer) from public, anon, authenticated;
grant execute on function s6dd_rehearsal.claim_voice_scoring(uuid, integer) to service_role;

set local lock_timeout = '5s';

-- ============================================================
-- pre-checks: prove this database is exactly "44 applied, 45 not"
-- ============================================================
do $$
declare
  v_result text;
  v_count  integer;
  v_type   text;
begin
  -- (1) migration 44's column is present
  if not exists (select 1 from information_schema.columns
      where table_schema = 's6dd_rehearsal' and table_name = 'voice_explanations'
        and column_name = 'scoring_claimed_at') then
    raise exception 'pre-check: scoring_claimed_at missing - migration 44 is not applied here; refusing to run 45';
  end if;

  -- (2) exactly one claim_voice_scoring, with 44's signature and boolean result
  select count(*) into v_count from pg_proc
   where pronamespace = 's6dd_rehearsal'::regnamespace and proname = 'claim_voice_scoring';
  if v_count <> 1 then
    raise exception 'pre-check: expected exactly 1 claim_voice_scoring, found % - refusing to run', v_count;
  end if;
  select pg_get_function_result(oid) into v_result from pg_proc
   where pronamespace = 's6dd_rehearsal'::regnamespace and proname = 'claim_voice_scoring'
     and oidvectortypes(proargtypes) = 'uuid, integer';
  if v_result is null then
    raise exception 'pre-check: claim_voice_scoring(uuid, integer) not found - refusing to run';
  end if;
  if v_result <> 'boolean' then
    raise exception 'pre-check: claim_voice_scoring(uuid,integer) returns % (expected boolean) - this database is already past migration 44 (likely 45 is applied); refusing to drop and recreate it', v_result;
  end if;

  -- (3) 45's other two functions must not exist in ANY shape yet
  if exists (select 1 from pg_proc where pronamespace = 's6dd_rehearsal'::regnamespace
              and proname in ('complete_voice_scoring', 'fail_voice_scoring')) then
    raise exception 'pre-check: complete_voice_scoring / fail_voice_scoring already exist - database is not in the expected "44 only" state; refusing to run';
  end if;

  -- (4) the lease column must be absent, or already uuid (never another type)
  select data_type into v_type from information_schema.columns
   where table_schema = 's6dd_rehearsal' and table_name = 'voice_explanations'
     and column_name = 'scoring_lease_token';
  if v_type is not null and v_type <> 'uuid' then
    raise exception 'pre-check: scoring_lease_token exists with type % (expected uuid) - refusing to run', v_type;
  end if;

  -- (5) columns the new functions write must exist. plpgsql does NOT
  -- check these at CREATE time - a missing one would only fail later, at
  -- runtime, inside voice-score.
  select count(*) into v_count from information_schema.columns
   where table_schema = 's6dd_rehearsal' and table_name = 'voice_explanations'
     and column_name in ('id', 'status', 'communication_score', 'communication_notes');
  if v_count <> 4 then
    raise exception 'pre-check: voice_explanations is missing one of id/status/communication_score/communication_notes (found % of 4)', v_count;
  end if;

  -- (6) gen_random_uuid() (used by the new claim) resolves
  if to_regprocedure('gen_random_uuid()') is null then
    raise exception 'pre-check: gen_random_uuid() not available';
  end if;

  -- (7) FORCE RLS off, so the owner-run functions are not filtered by RLS
  if exists (select 1 from pg_class where oid = 's6dd_rehearsal.voice_explanations'::regclass
              and relforcerowsecurity) then
    raise exception 'pre-check: voice_explanations has FORCE ROW LEVEL SECURITY - the scoring functions would silently update 0 rows; refusing to run';
  end if;

  -- (8) the status CHECK still allows every value these functions write
  if not exists (select 1 from pg_constraint
                  where conrelid = 's6dd_rehearsal.voice_explanations'::regclass and contype = 'c'
                    and pg_get_constraintdef(oid) like '%status%'
                    and pg_get_constraintdef(oid) like '%''scored''%'
                    and pg_get_constraintdef(oid) like '%''failed''%') then
    raise exception 'pre-check: no status CHECK constraint allowing scored and failed was found on voice_explanations';
  end if;

  raise notice 'Step 6DD pre-checks passed: database is at migration 44, not 45.';
end $$;

-- ============================================================
-- migration 45 body (verbatim statements)
-- ============================================================

alter table s6dd_rehearsal.voice_explanations
  add column if not exists scoring_lease_token uuid;

drop function if exists s6dd_rehearsal.claim_voice_scoring(uuid, integer);
create or replace function s6dd_rehearsal.claim_voice_scoring(_id uuid, _claim_ttl_seconds integer default 120)
returns table (claimed boolean, lease_token uuid)
language plpgsql
security definer
set search_path to 's6dd_rehearsal', 'pg_temp'
as $function$
declare
  _lease uuid := gen_random_uuid();
  n integer;
begin
  -- Step 6DD fix: a null, zero or negative TTL made every existing claim
  -- look stale at once, so any caller could take over a live claim.
  if _claim_ttl_seconds is null or _claim_ttl_seconds < 1 then
    raise exception 'claim_voice_scoring: _claim_ttl_seconds must be >= 1 (got %)', _claim_ttl_seconds;
  end if;
  update s6dd_rehearsal.voice_explanations
     set scoring_claimed_at = now(),
         scoring_lease_token = _lease
   where id = _id
     and status <> 'scored'
     and (scoring_claimed_at is null
          or scoring_claimed_at < now() - make_interval(secs => _claim_ttl_seconds));
  get diagnostics n = row_count;
  if n > 0 then
    return query select true, _lease;
  else
    return query select false, null::uuid;
  end if;
end $function$;

create or replace function s6dd_rehearsal.complete_voice_scoring(
  _id uuid, _lease_token uuid, _score integer, _notes text
)
returns boolean
language plpgsql
security definer
set search_path to 's6dd_rehearsal', 'pg_temp'
as $function$
declare n integer;
begin
  -- Step 6DD fix: voice-score grades 0-100 and clamps to that range
  -- (supabase/functions/voice-score/index.ts). The column itself has no
  -- CHECK, so the database now refuses anything else.
  if _score is null or _score < 0 or _score > 100 then
    raise exception 'complete_voice_scoring: _score must be 0-100 (got %)', _score;
  end if;
  update s6dd_rehearsal.voice_explanations
     set communication_score = _score,
         communication_notes = _notes,
         status = 'scored'
   where id = _id and scoring_lease_token = _lease_token
     and status <> 'scored';  -- Step 6DD fix: a saved score is final
  get diagnostics n = row_count;
  return n > 0;
end $function$;

create or replace function s6dd_rehearsal.fail_voice_scoring(
  _id uuid, _lease_token uuid, _notes text default null
)
returns boolean
language plpgsql
security definer
set search_path to 's6dd_rehearsal', 'pg_temp'
as $function$
declare n integer;
begin
  update s6dd_rehearsal.voice_explanations
     set status = 'failed',
         communication_notes = coalesce(_notes, communication_notes),
         scoring_claimed_at = null,
         scoring_lease_token = null
   where id = _id and scoring_lease_token = _lease_token
     and status <> 'scored';  -- Step 6DD fix: never turn a saved score into a failure
  get diagnostics n = row_count;
  return n > 0;
end $function$;

revoke all on function
  s6dd_rehearsal.claim_voice_scoring(uuid, integer),
  s6dd_rehearsal.complete_voice_scoring(uuid, uuid, integer, text),
  s6dd_rehearsal.fail_voice_scoring(uuid, uuid, text)
  from public, anon, authenticated;

grant execute on function
  s6dd_rehearsal.claim_voice_scoring(uuid, integer),
  s6dd_rehearsal.complete_voice_scoring(uuid, uuid, integer, text),
  s6dd_rehearsal.fail_voice_scoring(uuid, uuid, text)
  to service_role;

-- ============================================================
-- fail-closed verification, INSIDE the transaction, BEFORE commit.
-- Any failure raises, the transaction aborts, nothing is kept.
-- ============================================================
do $$
declare
  v_table_owner oid;
  v_fn record;
  v_acl record;
begin
  -- (a) new column, right type
  if not exists (select 1 from information_schema.columns
      where table_schema = 's6dd_rehearsal' and table_name = 'voice_explanations'
        and column_name = 'scoring_lease_token' and data_type = 'uuid') then
    raise exception 'post-check: scoring_lease_token uuid column missing';
  end if;
  if not exists (select 1 from information_schema.columns
      where table_schema = 's6dd_rehearsal' and table_name = 'voice_explanations'
        and column_name = 'scoring_claimed_at') then
    raise exception 'post-check: scoring_claimed_at column disappeared';
  end if;

  select relowner into v_table_owner from pg_class
   where oid = 's6dd_rehearsal.voice_explanations'::regclass;

  -- (b) exactly the three expected functions, expected shapes
  if (select count(*) from pg_proc where pronamespace = 's6dd_rehearsal'::regnamespace
       and proname in ('claim_voice_scoring', 'complete_voice_scoring', 'fail_voice_scoring')) <> 3 then
    raise exception 'post-check: expected exactly 3 voice scoring functions (no stray overloads)';
  end if;

  for v_fn in
    select p.oid, p.proname, oidvectortypes(p.proargtypes) as args,
           pg_get_function_result(p.oid) as result, p.prosecdef, p.proowner, p.proconfig
      from pg_proc p
     where p.pronamespace = 's6dd_rehearsal'::regnamespace
       and p.proname in ('claim_voice_scoring', 'complete_voice_scoring', 'fail_voice_scoring')
  loop
    if v_fn.proname = 'claim_voice_scoring'
       and (v_fn.args <> 'uuid, integer' or v_fn.result <> 'TABLE(claimed boolean, lease_token uuid)') then
      raise exception 'post-check: claim_voice_scoring is (%) -> % (expected (uuid, integer) -> TABLE(claimed boolean, lease_token uuid))', v_fn.args, v_fn.result;
    end if;
    if v_fn.proname = 'complete_voice_scoring'
       and (v_fn.args <> 'uuid, uuid, integer, text' or v_fn.result <> 'boolean') then
      raise exception 'post-check: complete_voice_scoring is (%) -> %', v_fn.args, v_fn.result;
    end if;
    if v_fn.proname = 'fail_voice_scoring'
       and (v_fn.args <> 'uuid, uuid, text' or v_fn.result <> 'boolean') then
      raise exception 'post-check: fail_voice_scoring is (%) -> %', v_fn.args, v_fn.result;
    end if;
    if v_fn.proname = 'complete_voice_scoring'
       and position('and status <> ''scored''' in (select prosrc from pg_proc where oid = v_fn.oid)) = 0 then
      raise exception 'post-check: complete_voice_scoring lacks the Step 6DD "status <> scored" guard';
    end if;
    if v_fn.proname = 'complete_voice_scoring'
       and position('_score < 0 or _score > 100' in (select prosrc from pg_proc where oid = v_fn.oid)) = 0 then
      raise exception 'post-check: complete_voice_scoring lacks the Step 6DD 0-100 score guard';
    end if;
    if v_fn.proname = 'claim_voice_scoring'
       and position('_claim_ttl_seconds < 1' in (select prosrc from pg_proc where oid = v_fn.oid)) = 0 then
      raise exception 'post-check: claim_voice_scoring lacks the Step 6DD TTL guard';
    end if;
    if v_fn.proname = 'fail_voice_scoring'
       and position('and status <> ''scored''' in (select prosrc from pg_proc where oid = v_fn.oid)) = 0 then
      raise exception 'post-check: fail_voice_scoring lacks the Step 6DD "status <> scored" guard';
    end if;
    if not v_fn.prosecdef then
      raise exception 'post-check: % is not SECURITY DEFINER', v_fn.proname;
    end if;
    if v_fn.proconfig is null or not ('search_path=s6dd_rehearsal, pg_temp' = any (v_fn.proconfig)) then
      raise exception 'post-check: % has no pinned search_path (got %)', v_fn.proname, v_fn.proconfig;
    end if;
    -- same owner as the table, so SECURITY DEFINER runs as the table owner
    if v_fn.proowner <> v_table_owner then
      raise exception 'post-check: % owned by %, table owned by % - owners must match',
        v_fn.proname, v_fn.proowner::regrole::text, v_table_owner::regrole::text;
    end if;

    -- (c) EXECUTE: service_role yes; anon, authenticated, PUBLIC no
    if not has_function_privilege('service_role', v_fn.oid, 'EXECUTE') then
      raise exception 'post-check: % missing service_role EXECUTE', v_fn.proname;
    end if;
    if has_function_privilege('anon', v_fn.oid, 'EXECUTE') then
      raise exception 'post-check: anon can EXECUTE %', v_fn.proname;
    end if;
    if has_function_privilege('authenticated', v_fn.oid, 'EXECUTE') then
      raise exception 'post-check: authenticated can EXECUTE %', v_fn.proname;
    end if;
    for v_acl in
      select a.grantee, a.privilege_type
        from aclexplode(coalesce((select proacl from pg_proc where oid = v_fn.oid),
                                 acldefault('f', v_fn.proowner))) a
    loop
      if v_acl.grantee = 0 then
        raise exception 'post-check: % still grants EXECUTE to PUBLIC', v_fn.proname;
      end if;
      if v_acl.grantee::regrole::text <> 'service_role' and v_acl.grantee <> v_fn.proowner then
        raise exception 'post-check: % grants % to % (expected only service_role or the owner)',
          v_fn.proname, v_acl.privilege_type, v_acl.grantee::regrole::text;
      end if;
    end loop;
  end loop;

  -- (d) regression guard: already-applied production state (41-44, 47)
  if has_table_privilege('authenticated', 's6dd_rehearsal.voice_explanations', 'UPDATE') then
    raise exception 'regression: authenticated has UPDATE on voice_explanations';
  end if;
  if has_table_privilege('anon', 's6dd_rehearsal.voice_explanations', 'UPDATE') then
    raise exception 'regression: anon has UPDATE on voice_explanations';
  end if;
  if not has_table_privilege('service_role', 's6dd_rehearsal.voice_explanations', 'UPDATE') then
    raise exception 'regression: service_role lost UPDATE on voice_explanations';
  end if;
  if not exists (select 1 from pg_class where oid = 's6dd_rehearsal.voice_explanations'::regclass
                  and relrowsecurity and not relforcerowsecurity) then
    raise exception 'regression: RLS must be enabled (and FORCE off) on voice_explanations';
  end if;
  if to_regprocedure('s6dd_rehearsal.guard_voice_explanations_insert()') is null then
    raise exception 'regression: guard_voice_explanations_insert() (migration 43) is missing';
  end if;

  raise notice 'Step 6DD: all fail-closed checks passed. Committing.';
end $$;

-- behaviour checks on the rehearsal copy (still inside the transaction)
do $$
declare
  r1 uuid := gen_random_uuid();
  r2 uuid := gen_random_uuid();
  r3 uuid := gen_random_uuid();
  c record; t1 uuid; t2 uuid; ok boolean; v record;
  r4 uuid := gen_random_uuid();
  r5 uuid := gen_random_uuid();
  r6 uuid := gen_random_uuid();
  raised boolean;
begin
  -- run as PostgREST would for voice-score: service_role JWT claims
  perform set_config('request.jwt.claims', '{"role":"service_role"}', true);
  insert into s6dd_rehearsal.voice_explanations (id) values (r1), (r2), (r3), (r4), (r5), (r6);

  select * into c from s6dd_rehearsal.claim_voice_scoring(r1);
  if not c.claimed or c.lease_token is null then raise exception 'F1 first claim failed'; end if;
  t1 := c.lease_token;

  select * into c from s6dd_rehearsal.claim_voice_scoring(r1);
  if c.claimed or c.lease_token is not null then raise exception 'F2 second claim on a fresh lease was allowed'; end if;

  if s6dd_rehearsal.complete_voice_scoring(r1, gen_random_uuid(), 50, 'forged') then
    raise exception 'F3 complete with a wrong token was accepted'; end if;

  update s6dd_rehearsal.voice_explanations set scoring_claimed_at = now() - interval '200 seconds' where id = r1;
  select * into c from s6dd_rehearsal.claim_voice_scoring(r1);
  if not c.claimed or c.lease_token = t1 then raise exception 'F4 stale lease was not taken over with a new token'; end if;
  t2 := c.lease_token;

  if s6dd_rehearsal.complete_voice_scoring(r1, t1, 10, 'late write from the expired claim') then
    raise exception 'F5 late complete from the expired lease was accepted'; end if;
  if s6dd_rehearsal.fail_voice_scoring(r1, t1, 'late fail') then
    raise exception 'F6 late fail from the expired lease released the new claim'; end if;
  select * into v from s6dd_rehearsal.voice_explanations where id = r1;
  if v.communication_score is not null or v.status <> 'recorded' then
    raise exception 'F7 row changed by a rejected write'; end if;

  if not s6dd_rehearsal.complete_voice_scoring(r1, t2, 80, 'ok') then raise exception 'F8 valid complete rejected'; end if;
  select * into v from s6dd_rehearsal.voice_explanations where id = r1;
  if v.status <> 'scored' or v.communication_score <> 80 then raise exception 'F9 score not saved'; end if;

  select * into c from s6dd_rehearsal.claim_voice_scoring(r1);
  if c.claimed then raise exception 'F10 claim allowed on an already scored row'; end if;

  select * into c from s6dd_rehearsal.claim_voice_scoring(r2);
  if not s6dd_rehearsal.fail_voice_scoring(r2, c.lease_token, 'boom') then raise exception 'F11 valid fail rejected'; end if;
  select * into v from s6dd_rehearsal.voice_explanations where id = r2;
  if v.status <> 'failed' or v.scoring_claimed_at is not null or v.scoring_lease_token is not null then
    raise exception 'F12 fail did not release the claim'; end if;

  -- F13/F14: the Step 6DD race. A late or repeated fail carrying the
  -- SAME token that just saved a score must not undo the score.
  select * into c from s6dd_rehearsal.claim_voice_scoring(r3);
  if not s6dd_rehearsal.complete_voice_scoring(r3, c.lease_token, 70, 'good') then raise exception 'F13a complete rejected'; end if;
  if s6dd_rehearsal.fail_voice_scoring(r3, c.lease_token, 'late fail after success') then
    raise exception 'F13 late fail with the same token was accepted on a scored row'; end if;
  select * into v from s6dd_rehearsal.voice_explanations where id = r3;
  if v.status <> 'scored' or v.communication_score <> 70 or v.communication_notes <> 'good' then
    raise exception 'F14 scored row was changed by a late fail (status %, score %)', v.status, v.communication_score; end if;

  -- F15/F16: a repeated complete with the SAME token must not overwrite
  -- the saved score.
  if s6dd_rehearsal.complete_voice_scoring(r3, c.lease_token, 5, 'overwrite attempt') then
    raise exception 'F15 repeated complete with the same token was accepted on a scored row'; end if;
  select * into v from s6dd_rehearsal.voice_explanations where id = r3;
  if v.status <> 'scored' or v.communication_score <> 70 or v.communication_notes <> 'good' then
    raise exception 'F16 saved score was overwritten (score %, notes %)', v.communication_score, v.communication_notes; end if;

  -- F17-F19: invalid TTL must raise, never take over a live claim
  select * into c from s6dd_rehearsal.claim_voice_scoring(r4);   -- live claim on r4
  t1 := c.lease_token;
  raised := false; begin perform s6dd_rehearsal.claim_voice_scoring(r4, 0); exception when others then raised := true; end;
  if not raised then raise exception 'F17 TTL 0 accepted'; end if;
  raised := false; begin perform s6dd_rehearsal.claim_voice_scoring(r4, null); exception when others then raised := true; end;
  if not raised then raise exception 'F18 TTL null accepted'; end if;
  raised := false; begin perform s6dd_rehearsal.claim_voice_scoring(r4, -5); exception when others then raised := true; end;
  if not raised then raise exception 'F19 negative TTL accepted'; end if;
  if (select scoring_lease_token from s6dd_rehearsal.voice_explanations where id = r4) <> t1 then
    raise exception 'F19b live lease changed by an invalid-TTL call'; end if;

  -- F20-F22: score outside 0-100 or null must raise and change nothing
  raised := false; begin perform s6dd_rehearsal.complete_voice_scoring(r4, t1, 101, 'x'); exception when others then raised := true; end;
  if not raised then raise exception 'F20 score 101 accepted'; end if;
  raised := false; begin perform s6dd_rehearsal.complete_voice_scoring(r4, t1, -1, 'x'); exception when others then raised := true; end;
  if not raised then raise exception 'F21 score -1 accepted'; end if;
  raised := false; begin perform s6dd_rehearsal.complete_voice_scoring(r4, t1, null, 'x'); exception when others then raised := true; end;
  if not raised then raise exception 'F22 null score accepted'; end if;
  if (select status from s6dd_rehearsal.voice_explanations where id = r4) <> 'recorded' then
    raise exception 'F22b row changed by a rejected score'; end if;

  -- F23/F24: boundaries 0 and 100 are valid
  if not s6dd_rehearsal.complete_voice_scoring(r4, t1, 0, 'zero') then raise exception 'F23 score 0 rejected'; end if;
  select * into c from s6dd_rehearsal.claim_voice_scoring(r5);
  if not s6dd_rehearsal.complete_voice_scoring(r5, c.lease_token, 100, 'hundred') then raise exception 'F24 score 100 rejected'; end if;

  -- F25-F27: null / unknown inputs match nothing
  if s6dd_rehearsal.complete_voice_scoring(r6, null, 50, 'x') then raise exception 'F25 null token complete accepted'; end if;
  if s6dd_rehearsal.fail_voice_scoring(r6, null, 'x') then raise exception 'F26 null token fail accepted'; end if;
  select * into c from s6dd_rehearsal.claim_voice_scoring(null);
  if c.claimed then raise exception 'F27 null id claimed'; end if;
  select * into c from s6dd_rehearsal.claim_voice_scoring(gen_random_uuid());
  if c.claimed then raise exception 'F28 unknown id claimed'; end if;

  -- F29: success after failure with the old token is rejected
  select * into c from s6dd_rehearsal.claim_voice_scoring(r6);
  t1 := c.lease_token;
  if not s6dd_rehearsal.fail_voice_scoring(r6, t1, 'boom') then raise exception 'F29a fail rejected'; end if;
  if s6dd_rehearsal.complete_voice_scoring(r6, t1, 60, 'late success') then
    raise exception 'F29 complete accepted after the lease was released by fail'; end if;

  -- F30: retry path - a failed row can be claimed again and scored
  select * into c from s6dd_rehearsal.claim_voice_scoring(r6);
  if not c.claimed or c.lease_token = t1 then raise exception 'F30a failed row not re-claimable'; end if;
  if not s6dd_rehearsal.complete_voice_scoring(r6, c.lease_token, 60, 'retry ok') then raise exception 'F30 retry score rejected'; end if;
  select * into v from s6dd_rehearsal.voice_explanations where id = r6;
  if v.status <> 'scored' or v.communication_score <> 60 then raise exception 'F30b retry not saved'; end if;

  raise notice 'Step 6DD rehearsal: all 30 behaviour checks passed (F1-F30).';
end $$;

rollback;
