"""Turn content/syllabus/*.json into ONE migration: migration/28-syllabus.sql. Nothing is sent to the database here.

What it does to the live curriculum (all inside one transaction):
  * every OLD topic stays, with its rows, lessons and quizzes (so no student's progress moves or breaks);
  * every step the syllabus has that a track does not yet teach becomes a NEW topic (only the seed row + its
    step list in level_syllabus; the lesson itself is written later, once, by the course builder);
  * topics are renumbered into syllabus order (two-phase, so the unique key never collides);
  * student_tracks.unlocked_through / placed_at_level are remapped so nothing a student had open gets locked;
  * track_phases are rebuilt as four equal parts of each track;
  * six new courses become new tracks.
usage: python apply_syllabus.py            -> writes migration/28-syllabus.sql and prints a summary
"""
import json, os, glob, collections, sys
from pl import token, http, API

HERE = os.path.dirname(__file__)
SYL = os.path.join(HERE, "..", "..", "content", "syllabus")
OUT = os.path.join(HERE, "..", "..", "migration", "28-syllabus.sql")
NEW_COURSES = {  # slug: (name, emoji, interest, role, skill)
    "python": ("Python", "🐍", "coding", "Python developer", "Python"),
    "java": ("Java and Spring", "☕", "coding", "Java backend developer", "Java"),
    "dsa": ("Data Structures and Algorithms", "🧩", "coding", "software engineer", "Data Structures"),
    "computer-science": ("Computer Science Foundations", "🖥️", "coding", "software engineer", "Computer Science"),
    "system-design": ("System Design", "🏗️", "coding", "backend engineer", "System Design"),
    "deep-learning": ("Deep Learning and LLMs", "🧠", "ai", "machine learning engineer", "Deep Learning"),
}
PHASES = ["Foundations", "Core Skills", "Real Systems", "Job Ready"]
q = lambda s: "'" + str(s).replace("'", "''") + "'"
H = lambda: {"Authorization": f"Bearer {token('svc')}"}


def get(path):
    st, out = http(f"{API}/{path}", headers=H(), method="GET")
    assert st == 200, (path, out)
    return out


def main():
    tracks = get("level_tracks?select=*&order=sort_order")
    levels = get("levels?select=id,track_slug,level_number,sub_level,kind,skill,title&order=track_slug,level_number,sub_level&limit=5000")
    st_rows = get("student_tracks?select=id,track_slug,placed_at_level,unlocked_through&limit=5000")
    sylls = {os.path.basename(f)[:-5]: json.load(open(f, encoding="utf-8")) for f in glob.glob(os.path.join(SYL, "*.json"))
             if not f.endswith((".hand.json", ".ai.json"))}
    by_track = collections.defaultdict(lambda: collections.defaultdict(list))
    for r in levels:
        by_track[r["track_slug"]][r["level_number"]].append(r)

    sql = ["-- 28: full syllabi. Generated by scripts/dev-tools/apply_syllabus.py from content/syllabus/*.json.",
           "begin;",
           "create table if not exists public.level_syllabus (",
           "  level_id uuid primary key references public.levels(id) on delete cascade,",
           "  why text, steps jsonb not null);",
           "alter table public.level_syllabus enable row level security;",
           "revoke all on public.level_syllabus from anon, authenticated;",
           "grant all on public.level_syllabus to service_role;"]
    summary = []
    sort_base = max(t["sort_order"] for t in tracks)
    for slug, (name, emoji, interest, role, skill) in NEW_COURSES.items():
        if slug not in [t["slug"] for t in tracks]:
            sort_base += 1
            sql.append(f"insert into public.level_tracks (slug,name,emoji,interest,role,sort_order) values "
                       f"({q(slug)},{q(name)},{q(emoji)},{q(interest)},{q(role)},{sort_base}) on conflict (slug) do nothing;")

    all_slugs = [t["slug"] for t in tracks] + [s for s in NEW_COURSES if s not in [t["slug"] for t in tracks]]
    for slug in all_slugs:
        S = sylls.get(slug)
        if not S:
            summary.append((slug, "no syllabus", 0, 0))
            continue
        old = by_track.get(slug, {})
        title_to_old = {}
        for n, rows in old.items():
            for r in rows:
                if r["kind"] == "explanation":
                    title_to_old[r["title"].strip().lower()] = n
        old_steps = {n: sum(1 for r in rows if r["kind"] == "explanation") for n, rows in old.items()}
        claimed, key, newtopics = {}, {}, []
        for i, t in enumerate(S["topics"]):
            cnt = collections.Counter(title_to_old.get(s["title"].strip().lower()) for s in t["steps"] if s.get("existing"))
            cnt.pop(None, None)
            reuse = None
            for n, c in cnt.most_common():
                if n not in claimed and c >= max(1, 0.5 * old_steps.get(n, 1)):
                    reuse = n
                    break
            if reuse is not None:
                claimed[reuse] = i
            new_steps = [s["title"] for s in t["steps"] if title_to_old.get(s["title"].strip().lower()) is None]
            if new_steps:
                newtopics.append({"key": i + (0.5 if reuse is not None else 0.3), "title": t["title"] + (" — part 2" if reuse is not None else ""),
                                  "why": t.get("why", ""), "steps": new_steps,
                                  "skill": NEW_COURSES[slug][4] if slug in NEW_COURSES else t["title"]})
        # order keys for old topics
        for n in old:
            if n in claimed:
                key[n] = claimed[n]
            else:
                hits = [i for i, t in enumerate(S["topics"]) for s in t["steps"]
                        if title_to_old.get(s["title"].strip().lower()) == n]
                key[n] = (sum(hits) / len(hits) + 0.6) if hits else (n / max(len(old), 1)) * len(S["topics"]) + 0.6
        items = [("old", n, key[n]) for n in old] + [("new", j, nt["key"]) for j, nt in enumerate(newtopics)]
        items.sort(key=lambda x: (x[2], 0 if x[0] == "old" else 1, x[1]))
        remap = {}                                     # old n -> new n
        sql.append(f"-- {slug}: {len(old)} old topics kept, {len(newtopics)} new topics")
        if old:
            sql.append(f"update public.levels set level_number = level_number + 10000 where track_slug = {q(slug)};")
        for pos, (kind, ref, _) in enumerate(items, start=1):
            if kind == "old":
                remap[ref] = pos
                sql.append(f"update public.levels set level_number = {pos} where track_slug = {q(slug)} and level_number = {ref + 10000};")
            else:
                nt = newtopics[ref]
                sql.append("with s as (insert into public.levels (track_slug, level_number, sub_level, kind, skill, title) values "
                           f"({q(slug)}, {pos}, 1, 'explanation', {q(nt['skill'])}, {q(nt['title'])}) returning id) "
                           f"insert into public.level_syllabus (level_id, why, steps) select id, {q(nt['why'])}, {q(json.dumps(nt['steps'], ensure_ascii=False))}::jsonb from s;")
        total = len(items)
        # keep everything a student had open, open
        if old:
            cases_u = " ".join(f"when {o} then {max(v for k2, v in remap.items() if k2 <= o)}" for o in sorted(old))
            cases_p = " ".join(f"when {o} then {remap[o]}" for o in sorted(old))
            sql.append(f"update public.student_tracks set unlocked_through = case unlocked_through {cases_u} else greatest(unlocked_through, 1) end, "
                       f"placed_at_level = case placed_at_level when 0 then 0 {cases_p} else placed_at_level end where track_slug = {q(slug)};")
        # four equal parts
        sql.append(f"delete from public.track_phases where track_slug = {q(slug)};")
        for p in range(4):
            a, b = round(p * total / 4) + 1, round((p + 1) * total / 4)
            if b >= a:
                sql.append(f"insert into public.track_phases (track_slug, phase_number, name, from_level, to_level) values ({q(slug)}, {p + 1}, {q(PHASES[p])}, {a}, {b});")
        summary.append((slug, "ok", len(old), len(newtopics), sum(len(nt['steps']) for nt in newtopics)))
    sql.append("commit;")
    open(OUT, "w", encoding="utf-8").write("\n".join(sql) + "\n")
    print(f"{'track':20} old-topics new-topics new-steps")
    for s in summary:
        print(f"{s[0]:20} {s[2]:10} {s[3]:10} {s[4] if len(s) > 4 else ''}")
    print("written", os.path.abspath(OUT), len(sql), "statements")


if __name__ == "__main__":
    main()
