"""Export the curriculum STRUCTURE (no lesson text, no student data) from a local database where the
curriculum seed chain was replayed, as one data-only seed that can be loaded into staging.

    python scripts/dev-tools/export_curriculum_seed.py <psql-conn-args...> > seed.sql

Rows are matched by natural key (track slug, topic number, sub-level) and inserted with
ON CONFLICT DO NOTHING, so rows that already exist on the target (e.g. protected fixtures) are left as
they are. No function, grant or policy is created or changed. No AI is involved.
"""
import csv, io, subprocess, sys

PSQL = r"C:\Program Files\PostgreSQL\17\bin\psql.exe"
CONN = sys.argv[1:]


def rows(sql):
    out = subprocess.run([PSQL, *CONN, "-X", "-q", "-c", f"copy ({sql}) to stdout with (format csv, header true)"],
                         capture_output=True, text=True, encoding="utf-8", check=True).stdout
    return list(csv.DictReader(io.StringIO(out)))


def lit(v):
    if v is None or v == "":
        return "null"
    return "'" + v.replace("'", "''") + "'"


def cols(table):
    return [r["column_name"] for r in rows(
        f"select column_name from information_schema.columns where table_schema='public' and table_name='{table}' order by ordinal_position")]


out = ["-- Curriculum structure seed (data only). Generated by scripts/dev-tools/export_curriculum_seed.py from a",
       "-- local replay of stage5 + stage43 + migrations 28, 30, 32, 34. No lesson text, no student data, no functions.",
       "begin;"]

tc = cols("level_tracks")
for r in rows("select * from public.level_tracks order by slug"):
    out.append(f"insert into public.level_tracks ({', '.join(tc)}) values ({', '.join(lit(r[c]) for c in tc)}) on conflict do nothing;")

pc = [c for c in cols("track_phases") if c != "id"]
for r in rows("select * from public.track_phases order by track_slug, phase_number"):
    out.append(f"insert into public.track_phases ({', '.join(pc)}) values ({', '.join(lit(r[c]) for c in pc)}) on conflict do nothing;")

for r in rows("select track_slug, level_number, sub_level, kind, skill, title from public.levels order by track_slug, level_number, sub_level"):
    out.append("insert into public.levels (track_slug, level_number, sub_level, kind, skill, title) values "
               f"({lit(r['track_slug'])}, {r['level_number']}, {r['sub_level']}, {lit(r['kind'])}, {lit(r['skill'])}, {lit(r['title'])}) on conflict do nothing;")

key = lambda r: f"l.track_slug = {lit(r['track_slug'])} and l.level_number = {r['level_number']} and l.sub_level = {r['sub_level']}"
for r in rows("select l.track_slug, l.level_number, l.sub_level, s.why, s.steps::text as steps from public.level_syllabus s join public.levels l on l.id = s.level_id order by 1, 2, 3"):
    out.append(f"insert into public.level_syllabus (level_id, why, steps) select l.id, {lit(r['why'])}, {lit(r['steps'])}::jsonb "
               f"from public.levels l where {key(r)} on conflict do nothing;")

for r in rows("select l.track_slug, l.level_number, l.sub_level, t.course_slug from public.topic_links t join public.levels l on l.id = t.level_id order by 1, 2"):
    out.append(f"insert into public.topic_links (level_id, course_slug) select l.id, {lit(r['course_slug'])} "
               f"from public.levels l where {key(r)} on conflict do nothing;")

for r in rows("select alias, skill from public.skill_aliases order by alias"):
    out.append(f"insert into public.skill_aliases (alias, skill) values ({lit(r['alias'])}, {lit(r['skill'])}) on conflict do nothing;")

out.append("""do $$ begin
  if (select count(*) from public.level_tracks) < 41 then raise exception 'curriculum seed: tracks'; end if;
  if (select count(*) from public.levels where sub_level = 1) < 814 then raise exception 'curriculum seed: topics'; end if;
  if (select count(*) from public.topic_links) < 47 then raise exception 'curriculum seed: topic_links'; end if;
  if exists (select 1 from public.topic_links tl where not exists (select 1 from public.level_tracks t where t.slug = tl.course_slug))
    then raise exception 'curriculum seed: link to a missing course'; end if;
end $$;
commit;""")
sys.stdout.reconfigure(encoding="utf-8")
print("\n".join(out))
