# Candidate learning repos per skill (first = main pick). Verified by check_repos.py.
C = {
 # web
 "HTML/CSS": ["microsoft/Web-Dev-For-Beginners", "mdn/content", "AllThingsSmitty/css-protips"],
 "JavaScript": ["leonardomso/33-js-concepts", "javascript-tutorial/en.javascript.info", "getify/You-Dont-Know-JS", "ryanmcdermott/clean-code-javascript"],
 "TypeScript": ["basarat/typescript-book", "type-challenges/type-challenges"],
 "React": ["reactjs/react.dev", "fullstack-hy2020/fullstack-hy2020.github.io", "enaqx/awesome-react"],
 "Tailwind": ["aniftyco/awesome-tailwindcss"],
 "Node.js": ["goldbergyoni/nodebestpractices", "sindresorhus/awesome-nodejs"],
 "Express": ["expressjs/expressjs.com", "fullstack-hy2020/fullstack-hy2020.github.io"],
 "SQL": ["enochtangg/quick-SQL-cheatsheet", "pingcap/awesome-database-learning"],
 "PostgreSQL": ["dhamaniasad/awesome-postgres"],
 "MongoDB": ["ramnes/awesome-mongodb"],
 "REST APIs": ["microsoft/api-guidelines", "public-apis/public-apis"],
 "JWT Auth": ["OWASP/CheatSheetSeries"],
 "Next.js": ["vercel/next.js", "unicodeveloper/awesome-nextjs"],
 "Vercel": ["vercel/examples"],
 "Vue.js": ["vuejs/docs", "vuejs/awesome-vue"],
 "Angular": ["PatrickJS/awesome-angular"],
 # mobile
 "Kotlin": ["Heapy/awesome-kotlin"],
 "Jetpack Compose": ["android/compose-samples", "jetpack-compose/jetpack-compose-awesome"],
 "Swift": ["swiftlang/swift-book", "matteocrippa/awesome-swift"],
 "SwiftUI": ["vlondon/awesome-swiftui"],
 "Flutter": ["flutter/samples", "Solido/awesome-flutter"],
 "Dart": ["dart-lang/site-www"],
 "JSON": ["mdn/content"],
 "Room": ["android/codelab-android-room-with-a-view"],
 "SQLite": ["planetopendata/awesome-sqlite"],
 "Firebase": ["firebase/quickstart-android", "firebase/quickstart-js"],
 "App Store Publishing": ["fastlane/fastlane"],
 "Java": ["iluwatar/java-design-patterns", "TheAlgorithms/Java", "akullpp/awesome-java", "spring-projects/spring-petclinic"],
 "React Native": ["jondot/awesome-react-native", "react/react-native-website"],
 # data / ml
 "Python": ["trekhleb/learn-python", "TheAlgorithms/Python", "vinta/awesome-python", "krahets/hello-algo"],
 "Pandas": ["guipsamora/pandas_exercises", "jvns/pandas-cookbook"],
 "NumPy": ["rougier/numpy-100"],
 "Statistics": ["jakevdp/PythonDataScienceHandbook", "CamDavidsonPilon/Probabilistic-Programming-and-Bayesian-Methods-for-Hackers"],
 "Matplotlib": ["rougier/matplotlib-tutorial", "rougier/scientific-visualization-book"],
 "Seaborn": ["jakevdp/PythonDataScienceHandbook"],
 "Excel": [],
 "Power BI": [],
 "Tableau": [],
 "Jupyter": ["markusschanta/awesome-jupyter"],
 "scikit-learn": ["ageron/handson-ml3", "microsoft/ML-For-Beginners"],
 "PyTorch": ["mrdbourke/pytorch-deep-learning", "pytorch/tutorials"],
 "Linear Algebra": ["fastai/numerical-linear-algebra", "ageron/handson-ml3"],
 "Probability": ["CamDavidsonPilon/Probabilistic-Programming-and-Bayesian-Methods-for-Hackers"],
 "Feature Engineering": ["microsoft/ML-For-Beginners", "ageron/handson-ml3"],
 "FastAPI": ["fastapi/fastapi", "mjhea0/awesome-fastapi"],
 "Docker": ["docker/awesome-compose", "veggiemonk/awesome-docker"],
 "Transformers": ["huggingface/course", "huggingface/transformers"],
 "LLM APIs": ["microsoft/generative-ai-for-beginners", "anthropics/claude-cookbooks", "openai/openai-cookbook"],
 "RAG": ["NirDiamant/RAG_Techniques", "microsoft/generative-ai-for-beginners"],
 "TensorFlow": ["tensorflow/docs"],
 # cloud / devops
 "AWS": ["open-guides/og-aws", "donnemartin/awesome-aws"],
 "EC2": ["open-guides/og-aws"], "S3": ["open-guides/og-aws"], "IAM": ["open-guides/og-aws"],
 "VPC": ["open-guides/og-aws"], "Lambda": ["open-guides/og-aws"],
 "Linux": ["jlevy/the-art-of-command-line", "trimstray/the-book-of-secret-knowledge"],
 "Networking": ["trimstray/the-book-of-secret-knowledge", "donnemartin/system-design-primer"],
 "Terraform": ["shuaibiyy/awesome-tf"],
 "Bash": ["denysdovhan/bash-handbook", "dylanaraps/pure-bash-bible"],
 "Kubernetes": ["kelseyhightower/kubernetes-the-hard-way", "ramitsurana/awesome-kubernetes"],
 "Azure": ["MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator", "MicrosoftDocs/azure-docs"],
 "GCP": ["GoogleCloudPlatform/training-data-analyst"],
 "Git": ["k88hudson/git-flight-rules", "git-tips/tips"],
 "CI/CD": ["cicdops/awesome-ciandcd", "bregman-arie/devops-exercises"],
 "GitHub Actions": ["sdras/awesome-actions"],
 "Prometheus": ["prometheus/docs"],
 "Grafana": ["grafana/grafana"],
 "Jenkins": ["jenkinsci/pipeline-examples"],
 # security
 "Windows": ["sbilly/awesome-security"],
 "Active Directory": ["infosecn1nja/AD-Attack-Defense"],
 "Splunk": ["splunk/security_content"],
 "Wazuh": ["wazuh/wazuh-documentation"],
 "Log Analysis": ["trimstray/the-book-of-secret-knowledge"],
 "Wireshark": ["sbilly/awesome-security"],
 "Nmap": ["jasonniebauer/Nmap-Cheatsheet"],
 "Burp Suite": ["snoopysecurity/awesome-burp-extensions"],
 "OWASP Top 10": ["OWASP/Top10", "OWASP/CheatSheetSeries", "OWASP/wstg"],
 "Security+": [],
 # ui/ux
 "Figma": ["goabstract/Awesome-Design-Tools"],
 "Auto Layout": [],
 "Design Systems": ["alexpate/awesome-design-systems"],
 "Wireframing": ["gztchan/awesome-design"],
 "Prototyping": ["goabstract/Awesome-Design-Tools"],
 "User Research": [],
 "Usability Testing": [],
 "Accessibility (WCAG)": ["brunopulis/awesome-a11y", "a11yproject/a11yproject.com"],
 # games
 "Unity": ["baba-s/awesome-unity-open-source-on-github"],
 "C#": ["quozd/awesome-dotnet"],
 "Unreal": ["insthync/awesome-unreal"],
 "C++": ["AnthonyCalandra/modern-cpp-features", "fffaraz/awesome-cpp"],
 "3D Maths": ["ellisonleao/magictools"],
 "Physics": ["ellisonleao/magictools"],
 "Blender": ["agmmnn/awesome-blender"],
 # blockchain
 "Solidity": ["Cyfrin/solidity-by-example.github.io", "ethereumbook/ethereumbook"],
 "Foundry": ["foundry-rs/book", "Cyfrin/foundry-full-course-cu"],
 "Hardhat": ["NomicFoundation/hardhat"],
 "ethers.js": ["ethers-io/ethers.js"],
 "viem": ["wevm/viem"],
 "EVM Internals": ["ethereumbook/ethereumbook"],
 "Smart Contract Security": ["crytic/building-secure-contracts"],
 # iot / robotics
 "C": ["oz123/awesome-c"],
 "ESP32": ["espressif/esp-idf", "agucova/awesome-esp"],
 "STM32": ["nhivp/Awesome-Embedded"],
 "I2C/SPI/UART": ["nhivp/Awesome-Embedded"],
 "FreeRTOS": ["FreeRTOS/FreeRTOS"],
 "MQTT": ["awesome-mqtt/awesome-mqtt"],
 "Sensors": ["HQarroum/awesome-iot"],
 "Circuits/PCB": ["nhivp/Awesome-Embedded"],
 "ROS 2": ["ros2/ros2_documentation"],
 "Control Systems": ["AtsushiSakai/PythonRobotics"],
 "OpenCV": ["opencv/opencv", "spmallick/learnopencv"],
 "Embedded Systems": ["nhivp/Awesome-Embedded"],
 "Gazebo": ["ros2/ros2_documentation"],
 # prompt engineering
 "Prompt Basics": ["anthropics/prompt-eng-interactive-tutorial", "dair-ai/Prompt-Engineering-Guide"],
 "Few-Shot Prompting": ["dair-ai/Prompt-Engineering-Guide"],
 "Chain-of-Thought Prompting": ["dair-ai/Prompt-Engineering-Guide"],
 "System Prompts": ["anthropics/prompt-eng-interactive-tutorial"],
 "Structured Output": ["openai/openai-cookbook"],
 "RAG Basics": ["NirDiamant/RAG_Techniques"],
 "Agentic Loops": ["NirDiamant/GenAI_Agents"],
 "Evaluating Prompts": ["anthropics/courses"],
 # aptitude / hr
 "STAR Response Basics": ["yangshun/tech-interview-handbook"],
 "Common HR Questions": ["yangshun/tech-interview-handbook"],
 "Strengths & Weaknesses Framing": ["yangshun/tech-interview-handbook"],
 "Salary Negotiation Basics": ["yangshun/tech-interview-handbook"],
}
