"""Writes docs/RELEASE-MANIFEST.md from what staging is ACTUALLY running (read-only).

    python scripts/release_manifest.py

The release is the set of artifacts proven on staging: one Git commit, one website build, one
image DIGEST per backend service (never a tag such as "latest"), and the migration files by
checksum. Production must receive exactly these.
"""
import json, os, re, subprocess, sys

P, R = "prooflab-508214", "asia-south1"
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sh = lambda c: subprocess.run(c, shell=True, capture_output=True, text=True, cwd=ROOT).stdout.strip()

head = sh("git rev-parse HEAD")
dirty = sh("git status --porcelain --untracked-files=no")
services = ["api", "auth-bridge", "functions", "files", "accounts", "code-runner", "transcriber", "transcription-worker"]
rows, images_commit = [], set()
for s in services:
    rev = sh(f'gcloud run services describe prooflab-staging-{s} --region={R} --project={P} --format="value(status.latestReadyRevisionName)"')
    d = json.loads(sh(f"gcloud run revisions describe {rev} --region={R} --project={P} --format=json"))
    image = d["spec"]["containers"][0]["image"]
    digest = d["status"]["imageDigest"].split("@")[-1]
    env = sorted(e["name"] for e in d["spec"]["containers"][0].get("env", []))
    m = re.search(r":stab-([0-9a-f]{7})(-\d+)?$", image)
    if m:
        images_commit.add(m.group(1) + (" (built from uncommitted files)" if m.group(2) else ""))
    rows.append((s, rev, image.split("/")[-1], digest, env))
jobs = []
for j in ("crawler", "bug-finder"):
    image = sh(f'gcloud run jobs describe prooflab-staging-{j} --region={R} --project={P} --format="value(spec.template.spec.template.spec.containers[0].image)"')
    digest = sh(f'gcloud artifacts docker images describe {image} --format="value(image_summary.digest)"')
    env = sh(f'gcloud run jobs describe prooflab-staging-{j} --region={R} --project={P} --format="value(spec.template.spec.template.spec.containers[0].env)"')
    jobs.append((j, image.split("/")[-1], digest, sorted(set(re.findall(r"'name': '([A-Z_]+)'", env)))))
    m = re.search(r":stab-([0-9a-f]{7})(-\d+)?$", image)
    if m:
        images_commit.add(m.group(1) + (" (built from uncommitted files)" if m.group(2) else ""))

plan = [l.split() for l in sh(f"{sys.executable} scripts/migrations.py plan").splitlines()]
run = json.loads(sh(f"gh run list --repo manitejakanuri1/prooflaab --commit {head} --json databaseId,conclusion --limit 1") or "[]")
artifact = ""
if run:
    log = sh(f"gh run view --repo manitejakanuri1/prooflaab {run[0]['databaseId']} --log")
    m = re.findall(r"([0-9a-f]{64})\s+dist\.sha256", log)
    artifact = m[-1] if m else ""
snapshot_commit = sh("git log -1 --format=%h -- infra")

out = [f"""# Release manifest

Generated by `scripts/release_manifest.py` from what **staging** is running. Production must receive exactly these artifacts - deploy by digest, never by tag, and do not rebuild.

| | |
|---|---|
| Git commit (source of everything below) | `{head}` |
| Branch | `work/stabilization` |
| Working tree when generated | {"clean" if not dirty else "NOT CLEAN - regenerate after committing"} |
| Images built from commit(s) | {", ".join(sorted(images_commit)) or "-"} |
| Website build (CI artifact `site-{head}`) | `dist.sha256` = `{artifact or "CI has not finished for this commit - re-run this script"}` |
| CI run | {("https://github.com/manitejakanuri1/prooflaab/actions/runs/" + str(run[0]["databaseId"]) + " (" + (run[0]["conclusion"] or "running") + ")") if run else "none yet"} |
| Gate | `scripts/dev-tools/staging_release_gate.sh` at this commit |
| Infrastructure snapshot | `infra/` at commit `{snapshot_commit}` |

## Backend images (by digest)

| Service | Staging revision | Image | Digest |
|---|---|---|---|"""]
for s, rev, image, digest, env in rows:
    out.append(f"| {s} | `{rev}` | `{image}` | `{digest}` |")
out.append("\n| Job | Image | Digest |\n|---|---|---|")
for j, image, digest, env in jobs:
    out.append(f"| {j} | `{image}` | `{digest}` |")
out.append("\nThe API is the public PostgREST image; production already runs the same version.\n")
out.append("## Setting names each service needs (names only; values are in Secret Manager or the rollout checklist)\n\n| Service | Settings |\n|---|---|")
for s, rev, image, digest, env in rows:
    out.append(f"| {s} | {', '.join(f'`{e}`' for e in env)} |")
for j, image, digest, env in jobs:
    out.append(f"| job {j} | {', '.join(f'`{e}`' for e in env)} |")
out.append("\nStaging values point at staging addresses. Production uses its own addresses and secrets; identity settings (`APP_SIGNING_KEY`, `APP_JWT_PUBLIC_JWKS`, `SIGNER_URL`, `SCHEDULER_*`, `CODE_RUNNER_AUTH`, `RUNNER_ALLOWED_CALLERS`, `PGRST_DB_PRE_REQUEST`) are switched on stage by stage (rollout checklist).\n")
out.append(f"## Migrations ({len(plan)} files under the ledger)\n\nApply through `python scripts/migrations.py wrap <file>`; the ledger refuses a file whose checksum differs.\n\n| File | SHA-256 |\n|---|---|")
for version, digest in plan:
    out.append(f"| `{version}.sql` | `{digest}` |")
out.append("\nOrder and grouping for production: see `PRODUCTION-ROLLOUT-CHECKLIST.md` stage 2 (66, 71, 72 are permanent drops and belong to stage 7).\n")
open(os.path.join(ROOT, "docs", "RELEASE-MANIFEST.md"), "w", encoding="utf-8", newline="\n").write("\n".join(out))
print("written docs/RELEASE-MANIFEST.md:", head[:7], "| images from", sorted(images_commit), "| artifact", artifact[:16] or "pending")
