// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zlfjxcwltqtajnczfjjp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpsZmp4Y3dsdHF0YWpuY3pmampwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEyODUzNDUsImV4cCI6MjA2Njg2MTM0NX0.KnW8HvUSMpPFj2pAEbuLZvSsf808KYcqXbQ-p3S1sOY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});